inveniosoftware/invenio

invenio/modules/pages/testsuite/__init__.py
invenio/modules/pages/testsuite/test_pages.py
invenio/modules/pages/views.py

* Restores the url_map after the request to avoid affecting
subsequent requests.

pages: global url_map modification fix

---

invenio/legacy/bibconvert/xslt_engine.py

* Adds support for document() usage in XSLT stylesheets for
the lxml processor.
* Removes Exception masking.
This was merged in master as 0f99378 
@tiborsimko  @jirikuncar

BibConvert: lxml support for local document()

---

invenio/ext/login/legacy_user.py
invenio/modules/accounts/models.py
invenio/modules/accounts/upgrades/accounts_2015_01_14_add_name_columns.py

* Adds corresponding upgrade recipe. (addresses #2647)

accounts: user full name addition to model

---

invenio/legacy/bibrank/adminlib.py

legacy: uft8 error fix websearch admin interface

---

invenio/ext/login/__init__.py

* Adds handler for `user_logged_in` signal that updates
`User.last_login` column.  (closes #2669)

login: fix last_login column update

---

invenio/modules/oauthclient/contrib/orcid.py

* Gets user full name upon login through ORCID and stores it.

oauthclient: orcid full name fetch

---

invenio/legacy/bibindex/adminlib.py
invenio/legacy/bibindex/engine_utils.py
invenio/legacy/bibrank/adminlib.py
invenio/modules/indexer/admin.py
invenio/modules/indexer/models.py
invenio/modules/indexer/utils.py

* Adds a admin interface for indexer developed with
Flask-Admin.

indexer: add admin interface

---

invenio/modules/knowledge/admin.py
invenio/modules/knowledge/api.py
invenio/modules/knowledge/forms.py
invenio/modules/knowledge/models.py
invenio/modules/knowledge/templates/knowledge/list.html
invenio/modules/knowledge/views.py

* Implements a new admin gui with Flask.
* Implements a listener to delete taxonomy files
automatically.

knowledge: implement new admin gui

---

invenio/ext/template/utils.py
invenio/modules/deposit/field_widgets.py
invenio/modules/deposit/templates/deposit/macros.html
invenio/modules/deposit/templates/deposit/macros_base.html

* Changes alignment of add button from right to left.

deposit: dynamic field add button alignment

---

modules/webstyle/doc/admin/webstyle-admin-guide.webdoc

* Enriches documentation related to detailed record page tabs.
(closes #216)

WebStyle: richer documentation on record page tabs

---

invenio/modules/authors/templates/authors/author_stub.html

Signed-off-by: Mateusz Susik <mateusz.susik@cern.ch>

authors: stub message for the old module

---

invenio/modules/knowledge/admin.py
invenio/modules/knowledge/forms.py

* Adds a control to update form model only when form
is submitted.

knowledge: fix update knowledge in admin interface

---

invenio/modules/oauthclient/handlers.py

oauthclient: PEP8/257 fixes

---

invenio/legacy/bibknowledge/admin.py
invenio/modules/knowledge/api.py
invenio/modules/knowledge/models.py
invenio/modules/knowledge/restful.py
invenio/modules/knowledge/testsuite/test_knowledge_restful.py
invenio/modules/knowledge/upgrades/knowledge_2015_01_22_add_slug_and_is_api_accessible_fields.py
invenio/utils/text.py

* Adds a new field slug in knowledge and a mechanism
to automatically generate it.
* Uses the slug as key in REST API instead of id.
* Adds a new field is_api_accessible to allow disabling
REST API access to a mapping.
(closes #2686)

knowledge: slugify and flag to access rest api

---

modules/bibindex/lib/bibindex_engine.py
modules/bibindex/lib/bibindex_regression_tests.py
modules/pdfchecker/lib/arxiv_pdf_checker_regression_tests.py

- BibIndex: fix new-old record incremental indexing
- BibIndex: clean up after authority regression test
- PdfChecker: clean up after regression tests

BibIndex: fix new-old record incremental indexing

---

invenio/modules/search/forms.py

* Replaces QuerySelectField with SelectField.
(addresses #2620)

search: removal of depreated WTForms extenstion

---

invenio/ext/script/__init__.py

* Fixes parser of remote RELEASE-NOTES.
Acked-by: Jiri Kuncar <jiri.kuncar@cern.ch>

base: fix url of RELEASE-NOTES

---

invenio/modules/access/admin.py
invenio/modules/accounts/forms.py
invenio/modules/groups/forms.py
invenio/modules/oauth2server/forms.py
invenio/modules/oauth2server/models.py
invenio/modules/oauthclient/forms.py
invenio/modules/search/admin.py
invenio/modules/tags/forms.py

* Replaces Required validator with DataRequired.
(addresses #2620)

global: removal of depreated WTForms extenstion

---

invenio/modules/records/models.py

records: Python 2.6 compatibility fix

---

invenio/modules/communities/models.py

* Allows search by id. (closes zenodo/zenodo#91)
* PEP8 Fixes.

communities: enabling search by id

---

invenio/modules/communities/forms.py

* Replaces Required validator with DataRequired. (addresses #2620)
* Fixes PEP8.

communities: replace deprecated WTForms validator

---

invenio/base/templates/admin_base.html

* Fixes JQuery and Select2 loading in Flask-Admin pages.
(addresses #2690)
Co-authored-by: Adrian Pawel Baran <adrian.pawel.baran@cern.ch>

base: fix jquery and select2 loading in admin

---

invenio/modules/oaiharvester/workflows/oaiharvest_record_approval.py
invenio/modules/oaiharvester/workflows/oaiharvest_record_post_process.py
invenio/modules/workflows/bundles.py
invenio/modules/workflows/definitions.py
invenio/modules/workflows/engine.py
invenio/modules/workflows/models.py
invenio/modules/workflows/static/js/workflows/holdingpen.js
invenio/modules/workflows/tasks/marcxml_tasks.py
invenio/modules/workflows/tasks/workflows_tasks.py
invenio/modules/workflows/templates/workflows/details_base.html
invenio/modules/workflows/templates/workflows/styles/harvesting_description.html
invenio/modules/workflows/utils.py
invenio/modules/workflows/views/holdingpen.py

A bundle of fixes that popped up during our INSPIRE labs testing.
Most notably is the ability to better extend the details page and "Need action" being a default selector of Holding Pen.

workflows: fixes

---

invenio/legacy/bibupload/engine.py
invenio/modules/deposit/field_base.py

* Fixes issue with record modification date due to regeneration of
recjson cached introduced in
16fcacc7fbeb4fbece1c44823f5f66437ca11483

bibupload: modification date fix

---

setup.py

* Enables automatic code changes detection. (closes #2778)
* Reduces CPU usage.

global: `watchdog` package addition

---

invenio/ext/logging/formatters.py
invenio/modules/formatter/engine.py
invenio/modules/formatter/testsuite/test_formatter_engine.py

* Fix formatter bug introduced in https://github.com/inveniosoftware/invenio/pull/2722#discussion-diff-23777064R2021 when no 001 tag is provided.
* Fix on exception formatting.

formatter: exception fixes

---

invenio/utils/shell.py

Signed-off-by: Dimitrios Semitsoglou-Tsiapos <dsemitso@cern.ch>

utils: `which` from distuitls

---

invenio/modules/communities/models.py
invenio/modules/communities/templates/communities/new_base.html
invenio/modules/communities/templates/communities/portalbox_upload_base.html

* Fixes delete modal dialog.
* Fixes template issues.

communities: bug fixes

---

modules/miscutil/lib/upgrades/invenio_2013_09_16_aidPERSONIDDATA_datablob.py
modules/miscutil/lib/upgrades/invenio_2014_08_12_format_code_varchar20.py
modules/miscutil/lib/upgrades/invenio_2015_03_03_tag_value.py
modules/miscutil/lib/upgrades/invenio_release_1_2_0.py
modules/miscutil/sql/tabcreate.sql

* f9f2ea64c77ee25dc7f64226245ade5b1ffbc924 installation: new release_1_2_0 upgrade recipe
* b06ba9b377639214b5c55f0d2cd873b2a7979ef2 installation: 2015_03_03_tag_value upgrade recipe
* 6f1c5be41ea9e30051680fbc306cc208f44ca6c8 installation: 2013_09_16_aidPERSONIDDATA fix
* 0432d58528a168a4f04ffe84159c991b5e8a19e7 installation: 2014_08_12_format upgrade recipe fix

Installation: complete upgrade recipes

---

modules/bibdocfile/lib/Makefile.am
modules/bibedit/lib/Makefile.am
modules/bibrank/etc/Makefile.am
modules/bibsched/lib/Makefile.am

* 44dddc2c08c6b49b4d857b8a7dfbaa68b9e07216 BibSched: completion of distribution files
* c75240a15c3bf304d81c26f2621f638313e8b8f6 BibRank: completion of distribution files
* 791c42e8bb8192ea2901e63d1b69660a89d378fb BibDocFile: completion of distribution files
* 507ba2f8fed031b52cb754e92ff2c204239ee037 BibEdit: addition of ticket template sub-directory

global: completion of distribution files

---

invenio/base/scripts/database.py
invenio/modules/editor/models.py

* Improves dropper script.
* PEP8/257 fixes.

base: table drop order fix

---

invenio/legacy/bibknowledge/webinterface.py

Already merged in master https://github.com/inveniosoftware/invenio/pull/2581.

bibknowledge: searchtype parameter addition

---

INSTALL.rst
package.json

* Adds package.json to simplify installation of npm packages.
* This allows as well to control what versions we install.
* Updates installation guide accordingly.

installation: package.json addition

---

.gitignore
AUTHORS
NEWS
RELEASE-NOTES
invenio/version.py
setup.cfg
setup.py

Invenio v2.0.0

---

.kwalitee.yml

kwalitee: valid component names

---

invenio/base/scripts/database.py
invenio/modules/search/models.py
invenio/modules/search/upgrades/search_2015_03_03_fix_models.py

* Fixes id_fieldvalue foreign keys to support Null value.
* PEP8/257 fixes.
(closes #2799)

search: fix foreign keys definition in models

---

invenio/ext/assets/extensions.py

* Avoids bundle changes from being cached when running in debug mode.
(fixes #2777)
Co-authored-by: Jiri Kuncar <jiri.kuncar@cern.ch>

assets: less debug fix

---

.travis.yml

* FIX Adds apache2 xsendfile package to installation process.
(addresses #2857)

travis: apache2 xsendfile installation

---

invenio/base/scripts/database.py

* Remove the workaround to drop the database in mysql.

base: foreign key check workaround removal

---

.travis.yml
docs/getting-started/overlay.rst

FIX Adds invenio.base package to the config.py file for a custom overlay in the docs
Signed-off-by: Jan Stypka jan.stypka@cern.ch

docs: invenio.base package addition

---

invenio/utils/deprecation.py

* NEW Deprecation policy comes with new deprecation warnings wrappers.
(closes #2875)
Co-authored-by: @lnielsen 

global: version specific deprecation warnings

---

invenio/modules/editor/models.py

editor: fix printing of before drop message

---

docs/api.rst
docs/modules/knowledge.rst
invenio/modules/knowledge/api.py

* Adds documentations for knowledge module.

knowledge: documentation addition

---

invenio/modules/knowledge/manage.py
invenio/modules/knowledge/utils.py

* NEW Adds manager to knowledge with a command to load
mappings into an existing knowledge base from a file.
E.g. `inveniomanage knowledge load kb_name /path/to/file.kb`

knowledge: manager addition

---

invenio/modules/oauthclient/templates/oauthclient/settings/index_base.html

oauthclient: extra template block addition

---

INSTALL.rst
invenio/base/bundles.py
invenio/base/static/js/admin.js
invenio/base/static/js/settings.js
invenio/base/templates/admin_base.html

* Replaces left over mentions of pu branch with master branch.

docs: pu mentions left overs

---

README.rst

* Adds Gitter.im button on README to advertise public Invenio
chat-room.

global: README gitter.im button

---

README.rst

global: svg Travis CI badge in README

---

invenio/base/templates/page_base.html

base: noscript warning language fix

---

invenio/modules/oauthclient/__init__.py

* Adds minor improvements about state token parameter to oauthclient
documentation.

oauthclient: state token documentation

---

.kwalitee.yml

kwalitee: valid component names (legacy)

---

invenio/modules/access/mailcookie.py

* fixes a few typos in the comments
* fixes a bug with the acc_add_user_role function call
Signed-off-by: Jan Stypka <jan.stypka@cern.ch>

access: mailcookie fix

---

invenio/modules/submit/upgrades/submit_2015_03_03_fix_models.py

* FIX Fixes upgrade recipe for SbmCOLLECTIONSbmCOLLECTION table
introduced in commit @1021055.
(closes #2954)

submit: upgrade recipe fix

---

.kwalitee.yml
Dockerfile
docker-compose.yml
invenio/base/factory.py

There is a initial Docker configuration for Invenio 2.x.  (addresses #2858)
--
cc @hachreak

docker: pythonic installation process

---

invenio/legacy/webcomment/webinterface.py
invenio/legacy/websession/webinterface.py

* Fixes imports from access module.
(addresses #2967)

global: access errors import fix

---

invenio/modules/accounts/templates/accounts/settings/helpers_base.html
invenio/modules/accounts/templates/accounts/settings/index_base.html

* Adds block panel_wrapper in helpers_base.html.
* Adds block panel_group in index_base.html.
Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

accounts: extra template block addition

---

invenio/modules/search/config.py
invenio/modules/search/testsuite/test_elasticsearch_walker.py
invenio/modules/search/walkers/elasticsearch.py

This branch adds tests for ensuring that the transformation from the invenio-query-parser produced AST is translated correctly into an elasticsearch-DSL query.

search: test elasticsearch visitor

---

invenio/modules/search/testsuite/test_elasticsearch_walker.py
invenio/modules/search/walkers/elasticsearch.py

* Fixes Single and Double quoted values
Signed-off-by: Marios Kogias <marioskogias@gmail.com>

search: fix in elasticsearch walker tests

---

Dockerfile

* NEW Adds new configurable variable `INVENIO_APP_CONFIG_ENVS` that can
be set both from `invenio.cfg` and OS environment. Application factory
iterates over comma separated list of configuration variable names and
updates application config with equivalent OS environment value.
(addresses #2858)
* AMENDS db8b055a6db2c01bcb174b2fee1c65723c9193bb

global: config values from environment variables

---

invenio/modules/knowledge/api.py

* Fixes documentation of a function.

knowledge: documentation fix

---

invenio/base/config.py
invenio/modules/formatter/format_elements/bfe_oai_marcxml.py

* FIX Switched names in config. (closes #2962)
* FIX Dummy variable not needed causing and error.
Signed-off-by: Jaime García <jaime.garcia.llopis@gmail.com>

OAIRepository: marcxml output format

---

docs/community/code-of-conduct.rst
docs/community/index.rst
docs/contents.rst.inc

Our community is growing, and as part of improving our community documentation #1799, we thought of adopting a Code of Conduct.   This PR proposes a text for discussion.
Design guidelines:
- should be short, sweet, no-nonsense
- should promote good collaborative development principles
Proposal:
- endorse literally the Python Code of Conduct
- recommend literally the egoless programming principles (TPOCP)
For the full text, please see the file `docs/community/code-of-conduct.rst`that  comes with this
PR.
Please comment on the text, upvote, downvote, or otherwise express your opinions.

RFC Code of Conduct

---

invenio/modules/access/control.py

* Improves unpacking of batch arguments.

access: code kwalitee improvements

---

invenio/modules/deposit/field_base.py
invenio/modules/deposit/validation_utils.py

* Adds validation to prevent removal of existing doi. (addresses zenodo/zenodo#231)

deposit: better doi validation in edit form

---

invenio/modules/access/admin.py
invenio/modules/access/views/admin.py
invenio/modules/collections/views/admin.py
invenio/modules/communities/admin/__init__.py
invenio/modules/indexer/admin.py
invenio/modules/pages/admin.py
invenio/modules/search/admin.py

* Forces unicode literals on admin.
(addresses #2967)

global: unicode literals for admins

---

invenio/ext/admin/views.py
invenio/ext/jasmine/views.py
invenio/modules/annotations/views.py
invenio/modules/authorprofiles/views.py
invenio/modules/cloudconnector/views.py
invenio/modules/communities/views.py
invenio/modules/documentation/views.py
invenio/modules/editor/views.py
invenio/modules/formatter/views.py
invenio/modules/groups/views.py
invenio/modules/knowledge/views.py
invenio/modules/linkbacks/views.py
invenio/modules/oaiharvester/views.py
invenio/modules/oairepository/views.py
invenio/modules/pages/views.py
invenio/modules/pidstore/views.py
invenio/modules/previewer/views.py
invenio/modules/records/views.py
invenio/modules/scheduler/views.py
invenio/modules/tags/views.py
invenio/modules/uploader/views.py

* Forces unicode literals on views. (addresses #2967)

global: unicode literals for views

---

invenio/utils/deprecation.py

global: post-release deprecation bump

---

invenio/legacy/oairepository/server.py

* Correctly handles getting single record from
restricted collection. (closes #2990)

oairepository: GetRecord fix

---

invenio/base/templates/mail_text.tpl
invenio/ext/babel/__init__.py
invenio/ext/babel/filters.py

* NEW Add datetime localization template filters.

babel: datetime localization template filters + email whitespace fix

---

invenio/legacy/oairepository/server.py

oairepository: resumption token user check

---

AUTHORS
INSTALL.rst
NEWS
README.rst
RELEASE-NOTES
RELEASE-NOTES.rst
invenio/version.py

- Invenio v2.0.2
- docs: "good luck" to "happy hacking"

Invenio v2.0.2

---

invenio/modules/oaiharvester/workflows/oaiharvest_harvest_repositories.py
invenio/modules/oaiharvester/workflows/oaiharvest_repository_with_approval.py
invenio/modules/workflows/tasks/workflows_tasks.py
invenio/modules/workflows/templates/workflows/styles/harvesting_description.html

Track and show children workflows in Holding Pen.

oaiharvest: spawned record tracking

---

.travis.yml

travis: pip upgrade addition

---

invenio/modules/accounts/upgrades/accounts_2015_03_06_namedefaults.py
invenio/modules/search/upgrades/search_2015_03_03_fix_models.py
invenio/modules/submit/upgrades/submit_2015_03_03_fix_models.py

Fixes upgrade recipes for databases coming from the legacy version.

upgrades: recipe fixes

---

docker-compose-dev.yml
docs/api.rst
docs/ext/script.rst
docs/getting-started/overlay.rst
invenio/ext/script/__init__.py

This reworks the way we're binding to network interfaces and ports in different situation. See commits for details.
Rebased against: `maint-2.0`

global: fix for multiple binding problems

---

.travis.yml
docker-compose-dev.yml
docs/api.rst
docs/ext/script.rst
docs/getting-started/overlay.rst
invenio/ext/logging/backends/sentry.py
invenio/ext/script/__init__.py

* Fixes a typo in sentry.py (app.extensions, not extension).
Signed-off-by: Sebastian Witowski <sebastian.witowski@cern.ch>

logging: fix sentry proxy

---

INSTALL.rst

installation: fix example CFG_SITE_URL

---

Dockerfile

* Slims down docker image by building on top of less bloated base image
and only install what is really required. Also purges unneeded
packages, flushes caches and clean temporary files. All these parts
should not be in a production image and are also not required by
developers. You can still install components when extending the
Invenio base image.
* Removes dpkg package docs from the production image because admins
should not use a slim docker image as a knowledge base.
* Sets correct MySQL username and db variable in boot script since we
rely on them and Invenio might change these defaults.

docker: image slim-down

---

invenio/modules/collections/cache.py

* Fixes `timestamp_verifier` to return the last time the collection
index was updated. (closes #3051)

collections: reclist cache fix

---

bower-base.json
invenio/base/bundles.py
invenio/base/static/less/footer.less
invenio/base/static/less/user-menu.less
invenio/base/templates/footer_base.html
invenio/base/templates/header_base.html
invenio/modules/accounts/templates/accounts/login_base.html
invenio/modules/search/bundles.py
invenio/modules/search/static/css/search/collection.css
invenio/modules/search/static/css/search/search.css
invenio/modules/search/templates/search/collection_base.html
invenio/modules/search/templates/search/form/tips_base.html
invenio/modules/search/templates/search/helpers_base.html

This fixes several issues I've found while playing around with our default fronend.
Rebaised against: `master`

template: several frontend fixes

---

invenio/ext/script/__init__.py

* NEW Implements optional TLS encryption directly by Werkzeug. Adds
many configuration variables (`SERVER_TLS_*`) to control the
behaviour.

script: TLS encryption

---

invenio/legacy/search_engine/__init__.py

* Addresses problem with creating record …
Co-authored: Jiri Kuncar <jiri.juncar@cern.ch>
Signed-off-by: Eamonn Maguire <eamonn.maguire@cern.ch>

search: fix get_record with only reserved recid

---

invenio/ext/script/__init__.py

* SECURITY Switches from insecure standard random number generator
to secure OS-driven entropy source (/dev/urandom on linux) for
secret key generation.

script: secure RNG for secret key generation

---

invenio/legacy/oairepository/server.py
invenio/modules/search/api.py
invenio/modules/search/config.py
invenio/modules/search/utils.py
invenio/modules/search/views/search.py

* NEW Adds new configuration option SEARCH_WALKERS which specifies
visitor classes that should be applied to a search query.

search: better engine configuration hooks

---

invenio/legacy/oaiharvest/web/admin/oaiharvestadmin.py

* FIX Fixes an issue with outputting the post-process arguments
when adding or editing an OAI source.
Without this fix, the legacy OAI harvest interface returns `500 Internal Server Error`.

legacy: OAI Harvest admin fix

---

invenio/modules/oauthclient/testsuite/test_views.py

* FIX Addresses problem with exception caused by malformed response
comming from an external OAuth2 server.  (closes #3029)

oauthclient: exception handling during response

---

invenio/legacy/bibsched/cli.py
invenio/legacy/bibsched/monitor.py

* Fixes MySQL ansi_quote problem for bibsched run_sql.
(addresses #3089)
--
cc @hachreak

legacy: fix run_sql ansi quotes in bibsched

---

invenio/legacy/batchuploader/engine.py
invenio/legacy/bibedit/cli.py
invenio/legacy/bibedit/utils.py
invenio/legacy/bibsched/monitor.py
invenio/legacy/bibsched/webapi.py
invenio/legacy/miscutil/solrutils_bibrank_indexer.py
invenio/legacy/webcomment/adminlib.py
invenio/legacy/webdoc/api.py
invenio/legacy/websearch_external_collections/__init__.py
invenio/legacy/webstat/engine.py
invenio/modules/access/control.py
invenio/modules/sequencegenerator/cnum.py

* Fixes MySQL ansi_quote problems for run_sql on many modules.
(addresses #3089)
* Fixes a utf-8 problem on OAIRepository Admin Guide.

legacy: fix run_sql ansi quotes

---

invenio/ext/babel/__init__.py
invenio/modules/workflows/engine.py
invenio/modules/workflows/models.py
invenio/modules/workflows/static/js/workflows/actions/approval.js
invenio/modules/workflows/static/js/workflows/actions/init.js
invenio/modules/workflows/static/js/workflows/common.js
invenio/modules/workflows/static/js/workflows/details.js
invenio/modules/workflows/static/js/workflows/details_actions.js
invenio/modules/workflows/static/js/workflows/details_actions_buttons.js
invenio/modules/workflows/static/js/workflows/init.js
invenio/modules/workflows/static/js/workflows/templates/alert.mustache
invenio/modules/workflows/templates/workflows/details_base.html
invenio/modules/workflows/templates/workflows/results/classifier.html
invenio/modules/workflows/templates/workflows/results/default.html
invenio/modules/workflows/templates/workflows/results/files.html
invenio/modules/workflows/templates/workflows/results/refextract.html
invenio/modules/workflows/templates/workflows/results/results_base.html
invenio/modules/workflows/templates/workflows/utils.html
invenio/modules/workflows/utils.py
invenio/modules/workflows/views/holdingpen.py

Updates to the Holding Pen details interface to have UI elements to delete and restart objects.

workflows: holding pen details update

---

invenio/modules/formatter/engine.py

* NOTE Invenio 1.x BFT template language and BFE elements are being
deprecated. Please migrate overlay output formats to use Jinja2.
(addresses #2662)

format: deprecation warnings for bfe and bft

---

invenio/modules/search/views/search.py

* BETTER The search results pages emits proper Cache and TTL
information in its HTTP headers, so that any eventual external
cachers (such as varnish) could act accordingly to invalidate their
caches automatically, without any configuration.  (closes #2302)
Reviewed-by: Tibor Simko <tibor.simko@cern.ch>

search: proper Cache and TTL info in HTTP headers

---

invenio/modules/access/models.py
invenio/modules/access/upgrades/__init__.py
invenio/modules/access/upgrades/access_2015_05_06_accROLE_accACTION_accARGUMENT_id.py

* Adds a recipe for upgrade the model. (addresses #3089)

access: fix model upgrade

---

invenio/modules/upgrader/commands.py

* Improves the recipe template.

upgrader: recipe template improvement

---

AUTHORS
MANIFEST.in
NEWS
RELEASE-NOTES
RELEASE-NOTES.rst
invenio/version.py

- bbb1ad3983b7fd44e4e6dd58b0e121bdd087e26c Invenio v2.0.3
- 04a3a815b8b4f228c2476de58e0f75f3724ffb9d matcher: fix argument types in jaro_fctn
- 7a122dab6847b1823d3248d2856cc06dd5e2496a legacy: lazy stopwords knowledge base

Invenio v2.0.3

---

modules/bibauthorid/lib/bibauthorid_webinterface.py

* SECURITY Improves URL redirecting by properly quoting all URL parts,
in order to better protect against possible XSS attacks.
Reviewed-by: Samuele Kaplun <samuele.kaplun@cern.ch>

BibAuthorID: safer URL redirecting

---

INSTALL
README
README.rst
configure.ac

* Rewords "Good luck" to "Happy hacking" in older maintenance branches
as well.
Reviewed-by: Ludmila Marian <ludmila.marian@gmail.com>

global: "good luck" to "happy hacking"

---

po/af.po
po/bg.po
po/ca.po
po/cs.po
po/de.po
po/el.po
po/en.po
po/es.po
po/fr.po
po/gl.po
po/hr.po
po/hu.po
po/it.po
po/ja.po
po/ka.po
po/no.po
po/pl.po
po/pt.po
po/ro.po
po/ru.po
po/rw.po
po/sk.po
po/sv.po
po/uk.po
po/zh_CN.po
po/zh_TW.po

I18N: PO file update for the release of v1.0.9

---

INSTALL
Makefile.am
NEWS
RELEASE-NOTES

Invenio v1.0.9

---

po/af.po
po/ar.po
po/bg.po
po/ca.po
po/cs.po
po/de.po
po/en.po
po/es.po
po/fr.po
po/gl.po
po/hr.po
po/hu.po
po/it.po
po/ja.po
po/ka.po
po/lt.po
po/no.po
po/pl.po
po/pt.po
po/ro.po
po/ru.po
po/rw.po
po/sk.po
po/sv.po
po/uk.po
po/zh_CN.po
po/zh_TW.po

I18N: PO file update for the release of v1.1.6

---

INSTALL
NEWS
RELEASE-NOTES

Invenio v1.1.6

---

po/af.po
po/ar.po
po/bg.po
po/ca.po
po/cs.po
po/de.po
po/el.po
po/en.po
po/es.po
po/fa.po
po/fr.po
po/gl.po
po/hr.po
po/hu.po
po/invenio.pot
po/it.po
po/ja.po
po/ka.po
po/lt.po
po/no.po
po/pl.po
po/pt.po
po/ro.po
po/ru.po
po/rw.po
po/sk.po
po/sv.po
po/uk.po
po/zh_CN.po
po/zh_TW.po

I18N: PO file update for the release of v1.2.1

---

INSTALL
NEWS
RELEASE-NOTES

Invenio v1.2.1

---

invenio/base/templates/paginate_base.html

* Makes diabled links non-clickable.

global: pagination compontent enhancement

---

Dockerfile
invenio/ext/session/interface.py
invenio/ext/session/legacy_session.py
invenio/utils/serializers.py
setup.py

* Upgrades session serialization to LZMA.
* Implements session signing. This avoids cache request for invalid
sessions and reduces the DDoS attack surface.
* Removes IP address storage+checks. This avoids data privacy issues and
enables users with multiple connections (e.g. WIFI+LTE, multiple WIFI
connections on trains+stations) to stay signed in.
* INCOMPATIBLE Drops all active sessions during upgrade. Might result in
log entries about non-restorable sessions.

RFC global: sessions 2.0

---

.editorconfig
scripts/setup_devmode.sh

Some changes for developers to simplify their life. May to go `master`, `maint-2.0` or `maint-2.1`.

global: useful changes for developers

---

invenio/modules/deposit/static/css/deposit/form.css
invenio/modules/deposit/templates/deposit/run_base.html
invenio/modules/deposit/templates/deposit/run_field_base.html
invenio/modules/deposit/templates/deposit/run_group_start_base.html
invenio/modules/deposit/templates/deposit/widget_plupload_base.html

Here are multiple small fronted fixes for the deposit module which I encountered while working on the analysis preservation code.

deposit: small fronted fixes

---

invenio/ext/template/__init__.py
invenio/modules/knowledge/templates/knowledge/list.html

closes #3118
--
@tiborsimko wait until I push new `maint-2.0`. Thanks

knowledge: fix html character encoding

---

invenio/ext/assets/commands.py

* Bumps bootstrap resolution version.
Co-authored-by: Marco Neumann <marco@crepererum.net>

assets: bootstrap resolution version bump

---

setup.py

* FIX Fixes capitalization of package names.

installation: package name capitalization fix

---

invenio/modules/deposit/static/js/deposit/uploader/uploaders/pluploader.js
invenio/modules/deposit/storage.py
setup.py

* BETTER Improves handling of large files in deposit.
* FIX Fixes issue with PLUpload chunking not being enabled.

deposit: large file performance improvement

---

invenio/modules/deposit/static/js/deposit/uploader/uploaders/pluploader.js
invenio/modules/deposit/storage.py
setup.py

* Fixes kwalitee issues in code.

deposit: kwalitee improvements

---

invenio/modules/editor/testsuite/test_editor.py

* Adds mocking of HTTP requests used in `perform_doi_search` to
'http://dx.doi.org/'.  (addresses #1986)
--
cc @jmartinm

editor: mocking of HTTP requests in tests

---

invenio/testsuite/__init__.py

* Adds useful functions to properly create and delete objects without
using bulk operations. (addresses #2419)

tests: methods for db session manipulation

---

invenio/ext/sqlalchemy/__init__.py
invenio/ext/sqlalchemy/types/legacyboolean.py

* Fix boolean conversion on database critical for PostgreSQL.
(closes #3215)

sqlalchemy: fix boolean value for PostgreSQL

---

invenio/modules/access/models.py

* Replaces AES SQLAlchemy internal function with passlib.
(closes #3219)

access: cookie creation refactoring

---

invenio/legacy/dbquery_mysql.py
invenio/legacy/dbquery_postgresql.py
invenio/testsuite/test_legacy_dbquery.py

* Adds new functions to permit the sql compatibility for MySQL and
PostgreSQL. (addresses #3214)

legacy: add functions to permit sql compatibility

---

invenio/modules/deposit/models.py
invenio/modules/deposit/testsuite/test_deposit_models.py

* Fixes the delete function to support cascading deletion on PostgreSQL.
(addresses #3218)

deposit: fix deleting function

---

invenio/modules/messages/dblayer.py
invenio/modules/messages/query.py

* Fixes sql queries to be more standard compliance: "RLIKE", quoting.
(addresses #3214)

messages: fix PostgreSQL compatibility

---

invenio/modules/accounts/templates/accounts/settings/helpers_base.html

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>
Reviewed-by: Javier Martin Montull <javier.martin.montull@cern.ch>

accounts: panel_start macro extra class parameter

---

invenio/modules/access/models.py

* FIX Fixes property id_accARGUMENT of AccAuthorization model.

access: fix id_accARGUMENT property

---

invenio/base/scripts/demosite.py
invenio/modules/authors/testsuite/test_authors_models.py
invenio/modules/comments/api.py
invenio/modules/oaiharvester/testsuite/test_tasks.py
invenio/modules/ranker/testsuite/test_donwloads_indexer.py
invenio/modules/records/testsuite/functions/get_number_of_copies.py
invenio/modules/sequencegenerator/backend.py
invenio/modules/sequencegenerator/texkey.py
invenio/modules/uploader/uploader_tasks.py
invenio/testsuite/test_legacy_dbquery.py

* Fixes run_sql query to obtain PostgreSQL compatibility.
(addresses #3089) (addresses #3214)

global: fix PostgreSQL compatibility

---

Dockerfile
docs/developers/docker.rst
invenio/base/factory.py
scripts/docker_boot.sh

Adds env variable to config the Invenio instance path and static folder. Uses this to improve the docker volume layout.

global: instance path and static folder config

---

invenio/base/utils.py
invenio/ext/script/__init__.py
setup.py

Fast integration for small improvements from #3307.

global: toposort utility and name extraction for cli

---

invenio/modules/accounts/models.py
invenio/modules/accounts/upgrades/accounts_2015_06_26_userext.py

* NOTE Changes id column from VARBINARY to String. (closes #3290)

accounts: userEXT model upgrade

---

docs/developers/docker.rst

* BETTER Improves Docker documentation notably related to how to work
with Invenio site overlays.
Reviewed-by: Marco Neumann <marco@crepererum.net>

docker: more complete overlay documentation

---

docker-compose.yml

* Fixes Docker compose config for production setup.

docker: fix for production compose config

---

invenio/utils/datastructures.py

global: `values` method addition to SmartDict

---

invenio/modules/search/templates/search/search_base.html
invenio/modules/search/views/search.py

* Resets pagination on facet click.  (closes #3353)

search: reseting jrec on facet click

---

invenio/modules/search/admin.py

* FIX Fixes admin interface for managing facets.  (closes #3333)

search: fix of facet admin interface

---

invenio/testsuite/test_ext_arxiv.py
invenio/testsuite/test_ext_crossref.py

* Fixes httpretty test which where disabled in 7348b08c.

global: fix httpretty test

---

NEWS
RELEASE-NOTES
RELEASE-NOTES.rst
invenio/version.py

Invenio v2.0.5

---

invenio/modules/knowledge/api.py

* Updates the dynamic knowledgebase API to use the new search API.
Depends on #3346 
@hachreak @jmartinm

knowledge: dynamic knowledgebase fix

---

.travis.yml

This is the `maint-2.0`-version of #3371

travis: speed up (maint-2.0)

---

invenio/legacy/search_engine/__init__.py
invenio/modules/indexer/nearest_terms.py

The rationale for the changes should be explained by https://github.com/inveniosoftware/invenio/issues/3271#issuecomment-114467703.

indexer: NameError fixing and related issues

---

invenio/modules/search/walkers/match_unit.py

search: match unit fix for Unicode characters

---

invenio/ext/es.py

elasticsearch: percolator fix for unmapped fields

---

invenio/base/bundles.py
invenio/base/static/css/admin.css
invenio/base/templates/admin-ng/layout.html
invenio/base/templates/admin_base.html
invenio/base/templates/admin_footer.html
invenio/base/templates/admin_footer_base.html
invenio/base/templates/admin_header.html
invenio/base/templates/admin_header_base.html
invenio/ext/admin/__init__.py
invenio/modules/access/admin.py
invenio/modules/knowledge/admin.py
invenio/modules/search/admin.py

* Using AdminLTE template built with Bootstrap 3.
* TODO: adapting each page view (which are shown in the main sidebar-menu) to the new template.

admin: next generation UI

---

invenio/utils/datastructures.py

I need this super call for proper inheritance in invenio-records.
Signed-off-by: Łukasz Chrząszcz <l.chrzaszcz@gmail.com>

global: super call addition to SmartDict

---

modules/bibformat/lib/elements/bfe_copyright.py

* BETTER Adds current year to the copyright statement.
Signed-off-by: Ludmila Marian <ludmila.marian@gmail.com>

BibFormat: add current year to copyright

---

invenio/testsuite/test_views.py

* Ports /ping endpoint used by HAProxy load balancer.  (closes #3471)

global: port of /ping endpoint

---

invenio/modules/accounts/forms.py
invenio/modules/annotations/views.py
invenio/modules/tags/views.py

global: PEP8 code style improvements

---

MANIFEST.in
NEWS
RELEASE-NOTES
RELEASE-NOTES.rst
invenio/version.py

Invenio v2.0.6

---

NEWS
RELEASE-NOTES
RELEASE-NOTES.rst
invenio/version.py

Invenio v2.1.1

---

invenio/ext/assets/filter.py

* NEW Implements CSSUrlFixer that can be used to fix hardcoded
`url(...)` entries in CSS files.
--
Ported from https://github.com/inveniosoftware/invenio-deposit/pull/6
cc @crepererum

assets: addition of CSSUrlFixer

---

.dockerignore
.gitignore
Dockerfile
INSTALL.rst
docker-compose-dev.yml
docs/developers/docker.rst
docs/getting-started/overlay.rst
requirements-devel.txt
scripts/docker_boot.sh
scripts/setup_devmode.sh

Takes over PR #3380 while @crepererum is away and cleans it for upstream merge.
Note: may require amendments to `invenio-base` now that the package was separated from Invenio.
- bf582ad3e62b3700cf0624b6f61d614e4b0dc91b docs: node.js => io.js
- 277682b3c8f3c30917f6707742f5c75178f20da8 installation: canonical jsonschemas location
- 39a2bbc1c1abda65e31dff033a8b287883326468 global: miscellaneous improvements
- bb503e3aa353efa3d69fe305e927573f751a9c59 global: PACKAGES_EXCLUDE fix for testing+docker
- 806a6a520b22cb78bbb1b852d59760c2bc8f8086 docker: Dockerfile optimizations
- 985fa62345cafc415be9f8aad690a06976833d51 docker: default lib level is `devel` in `master`
- 830faecabbef7abf9f989745779eb09b1c4676ed docker: Invenio config extention via overlay
- ff4dbf35180121a29e731da3e9045dcdaa76aebf …

docker-multiple-optimisations

---

invenio/legacy/bibrecord/__init__.py
invenio/legacy/dbquery_mysql.py
invenio/legacy/dbquery_postgresql.py
invenio/legacy/miscutil/__init__.py
invenio/legacy/miscutil/dbdump.py
invenio/legacy/registry.py
invenio/legacy/search_engine/__init__.py
invenio/legacy/search_engine/query_parser.py
invenio/legacy/webstyle/__init__.py
invenio/legacy/webstyle/templates.py
invenio/legacy/webuser.py
invenio/legacy/wsgi/__init__.py
invenio/legacy/wsgi/utils.py
invenio/testsuite/__init__.py
invenio/testsuite/helper.py
scripts/output_format_migration_kit.py

global: fix invenio_utils imports

---

MANIFEST.in
docs/installation/installation-detailed.rst
scripts/kickstart.sh

* NEW Initial release of `invenio3-kickstart` installation helper
script. Tested on Ubuntu 14.04 LTS (Trusty Tahr) and on CentOS 7.
* BETTER Completes detailed installation guide for Invenio v3.0.
(closes #3555)

scripts: addition of `invenio3-kickstart` script

---

docs/technology/git.rst

docs: note on optional next branch

---

invenio/base/templates/header_base.html

Adds more blocks to the header template to enable more customizations in the overlays.
Tind is using those.

base: new blocks for the header template

---

docs/installation/installation-detailed.rst
requirements-devel.txt
scripts/install.sh
scripts/provision-elasticsearch.sh
scripts/provision-postgresql.sh
scripts/provision-rabbitmq.sh
scripts/provision-redis.sh
scripts/provision-web.sh

- 114818fe242e99d1c8c7e871c8d3d20671fae9f1 installation: node provisioning package update
- fdf310271d56e732738fcf71ee14b4c6874a4a83 installation: development-friendly mode

Installation: development-friendly mode

---

Vagrantfile
docs/installation/installation-detailed.rst
requirements-devel.txt
scripts/install.sh
scripts/provision-web.sh
setup.py

* BETTER The provided example installation scripts now install the demo
records coming with `invenio-records` package.

installation: demo records

---

scripts/populate-instance.sh

* Updates script according to last change in invenio-accounts cli.
(addresses invenio-accounts#56)

scripts: update according to arguments unification

---

Dockerfile
docker-compose.yml

The explicit PATH settings should fix troubles observed by @egabancho @greut @switowski @kaplun 
@egabancho can you please test on your setup?

docker: explicit PATH environment settings

---

docker-compose.yml

docker: fix binding on 0.0.0.0

---

scripts/populate-instance.sh
scripts/provision-web.sh

scripts: update demo records loading

---

scripts/create-instance.sh
scripts/populate-instance.sh

scripts: OAIServer minimal configuration

---

.travis.yml
docs/modules/annotations.rst
invenio/modules/annotations/noteutils.py
invenio/modules/jsonalchemy/jsonext/parsers/description_parser.py
invenio/modules/jsonalchemy/jsonext/parsers/legacy_parser.py
invenio/modules/jsonalchemy/jsonext/parsers/memoize_parser.py
invenio/modules/jsonalchemy/jsonext/parsers/only_if_master_value_parser.py
invenio/modules/jsonalchemy/jsonext/parsers/only_if_parser.py
invenio/modules/jsonalchemy/jsonext/parsers/parse_first_parser.py
invenio/modules/jsonalchemy/jsonext/parsers/schema_parser.py
invenio/modules/oauthclient/__init__.py
invenio/modules/search/testsuite/test_search_external_collections_getter.py
setup.py

* FIX Adds upper limit on versions of several prerequisite packages,
fixing newly observed Invenio 2.0 demo site installation troubles.
Reported-by: Dmitri Pisarev <dimaip@gmail.com>

installation: fix prerequisite package versions

---

scripts/drop-instance.sh

installation: drop instance folder fix

---

INSTALL
Vagrantfile
scripts/create-instance.sh
scripts/drop-instance.sh
scripts/populate-instance.sh
scripts/provision-mysql.sh
scripts/provision-web.sh

* BETTER Installation scripts now support Ubuntu 14.04 LTS.

installation: support for Ubuntu 14.04 LTS

---

docs/community/chatrooms.rst
docs/processes/developing.rst
docs/processes/index.rst
docs/processes/integrating.rst
docs/processes/releasing.rst
docs/processes/reporting.rst
docs/processes/reviewing.rst
docs/processes/sprinting.rst
docs/processes/triaging.rst
docs/technology/i18n.rst

- 9335a0341cf3891209226d9380045228431c1edc docs: richer documentation about processes
- 1c259cb67a8d346435aa8772c1f2a9f3a849419f docs: chat room update

docs: richer documentation about processes

---

scripts/create-instance.sh

* Fixes default configuration of JSON schema host.  (closes #3646)
* Simplifies records REST endpoint configuration.  (closes #3636)

installation: JSON schema and records REST config

---

CHANGES.rst
RELEASE-NOTES.rst
invenio/version.py

release: v3.0.0a3

---

invenio/version.py

version: post-release bump

---

AUTHORS.rst
docs/technology/python.rst

docs: fix broken link

---

README.rst

docs: addition of kanban waffle badge

---

CONTRIBUTING.rst
INSTALL.rst
MANIFEST.in
RELEASE-NOTES.rst
Vagrantfile
docs/architecture/module-anatomy-models.rst
docs/architecture/package-anatomy-extensions.rst
docs/conf.py
docs/configuration/overlay.rst
docs/requirements.txt
docs/technology/docker.rst

docs: move to readthedocs.io

---

.tx/config
ABOUT-NLS
po/af.po
po/bg.po
po/ca.po
po/cs.po
po/de.po
po/el.po
po/es.po
po/fr.po
po/gl.po
po/hr.po
po/hu.po
po/it.po
po/ja.po
po/ka.po
po/no.po
po/pl.po
po/pt.po
po/ro.po
po/ru.po
po/rw.po
po/sk.po
po/sv.po
po/uk.po
po/zh_CN.po
po/zh_TW.po

- 11ee913106b5571913d509f7c31caca580a1fe7d I18N: Transifex-massaged PO files
- e5a49eb2a898b6dd56d9297aab87e220028681d7 I18N: initial Transifex configuration

I18N: Transifex for Invenio v1.0

---

docs/modules/list.rst

* Updates module list to include all recent Invenio packages and
standalone utilities.

docs: complete module list

---

requirements.txt

* Removes extra prerequisite line in `requirements.txt`.

installation: requirements simplification

---

scripts/provision-web.sh

installation: pinned node-sass to 3.8.0

---

NEWS
modules/websession/lib/inveniogc.py
po/de.po
po/es.po
po/fr.po
po/sk.po

* BETTER Updates German, French, Slovak and Spanish translations from Transifex.

I18N: translation updates

---

modules/bibupload/lib/bibupload.py

* FIX In case of replicating datasets between instances by means of OAI
harvesting it is plausible to check for external OAI-IDs not only in the field
specified by CFG_BIBUPLOAD_EXTERNAL_OAIID_TAG but also in CFG_OAI_ID_FIELD.
(closes #2812) (PR #2816)
* Note: find_record_from_oaiid() always returned the first record with a given
OAI-ID assuming that it is unique. However, due to manual intervention one may
have accidentially produced dupes here. Thus check, if more than one record
with an OAI-ID exists. If so, check if all records except one are deleted. In
this case return this surviving record, as cataloguers have resolved dupes
manually. In case we still have dupes resort to the old behaviour for sake of
compatibility, but at least throw a warning. This is somewhat of a TODO.
Probably …

bibupload: use CFG_OAI_ID_FIELD for deduping

---

INSTALL
NEWS
RELEASE-NOTES
po/sk.po

- d4654c31b75c6445eeb6daf04cd8b8755ce70e5a Invenio v1.1.7
- f98cbd72a46c22c9a5fe17371f81a3d4560bf583 I18N: translation updates

Invenio v1.1.7

---

modules/bibformat/lib/bibreformat.py
modules/bibindex/lib/bibindex_engine.py
modules/miscutil/lib/crossrefutils.py

- 6f928c1ea221de82cc820dd6b73a2107d4e3f92d crossrefutils: urlencode encoding
- 96f4027153dbd4cfdddada1b5b4ca56738b342ff BibFormat: outdated_caches() fix
- 2b598ecbb369fde1a55ccd7e647bc1ddf1fee410 BibIndex: infinite loop in beautify_range_list

PR #2758 #2824 #3516

---

INSTALL
NEWS
RELEASE-NOTES
config/invenio.conf
modules/bibdocfile/lib/bibdocfile_managedocfiles.py
modules/bibformat/lib/elements/bfe_edit_record.py
modules/bibindex/lib/tokenizers/BibIndexFulltextTokenizer.py
modules/miscutil/lib/solrutils_bibrank_indexer.py
modules/websearch/lib/search_engine.py
modules/websession/lib/webuser.py
modules/webstyle/lib/webinterface_handler_wsgi.py
modules/websubmit/lib/websubmit_file_converter.py
po/sk.po

Invenio v1.2.2

---

CHANGES.rst
RELEASE-NOTES.rst
invenio/version.py

release: v3.0.0a4

---

scripts/create-instance.sh
scripts/populate-instance.sh
scripts/provision-elasticsearch.sh
scripts/provision-postgresql.sh
scripts/provision-redis.sh
scripts/provision-web.sh
scripts/start-instance.sh

* FIX Fixes installation scripts regarding checking of environmental variables
and improves other minor issues such as better double quoting.

installation: environment variable checking

---

docs/introduction/releases.rst

* Adds information about new Invenio releases (v1.0.10, v1.1.7, v1.2.2).

docs: addition of new releases

---

AUTHORS.rst
Dockerfile
Vagrantfile
docs/installation/installation-detailed.rst
docs/installation/installation-quick.rst
scripts/create-instance.sh
scripts/provision-web.sh

- 5dc654e7d56408182ef1e3e9eed3a5d03c0a7a07 installation: CentOS7 instruction fixes
- d056e438148a66c90d2f87e109c9b369b2eb59cb docs: active/past contributor list update
- 0854138d1acbbdb4f1135d02a2156ac9c2ec515e installation: EPEL repository installation order
- b840e2ed2bfb2741301d21bd9f39a8697a224de0 installation: httpd_port_t setup for CentOS7
- fe65a8de198da09b6a5bb3e78eb7b9094bb5ec90 installation: MARC21 schema pinning
- 17568190d67f56400cf3a9b0321bc144151e4990 installation: clean-css pinning

installation fixes

---

docs/developersguide/tutorial/develop.rst

https://github.com/inveniosoftware/iugw2017/pull/15
Fully working example & tutorial

developersguide: develop tutorial

---

docs/developersguide/create-a-datamodel.rst

For the tutorial the README.rst of iugw2017/3-datamodels/custom-data-module will also be used.

WIP Datamodels doc

---

docs/usersguide/orcid-login.rst

WIP docs: orcid tutorial

---

docs/developersguide/tutorial/develop.rst

Uses the 3-datamodel tutorial as datamodel, this way the users can see the created records
Tutorial preview: https://github.com/drjova/iugw2017/tree/align-with-data-model/5-develop/tutorial

developersguide: update of the tutorial

---

docs/developersguide/tutorial/run-n-test.rst

- Fix a reference
- stop all flask applications before starting the tutorial

docs: update developer's guide

---

.inveniorc
Dockerfile
docker-compose.yml
docs/installation/installation-detailed.rst
docs/installation/installation-quick.rst
nginx/Dockerfile
nginx/invenio.conf
requirements-devel.txt
scripts/create-instance.sh
scripts/instance.cfg
scripts/populate-instance.sh
scripts/provision-postgresql.sh
scripts/provision-web.sh
scripts/start-instance.sh

* BETTER Updates Invenio demo site to use the new ILS flavour. Amends
installation scripts and documentation accordingly.
* Switches to using `invenio` instead of `invenio3` as the canonical instance
name.

installation: ILS demo site

---

docs/usersguide/accessing.rst
docs/usersguide/loading.rst
docs/usersguide/quickstart.rst
docs/usersguide/running.rst
docs/usersguide/tutorial/configure.rst
docs/usersguide/tutorial/customize.rst
docs/usersguide/tutorial/index.rst
docs/usersguide/tutorial/install.rst
docs/usersguide/tutorial/prerequisites.rst
docs/usersguide/tutorial/records.rst

* Initial release of user guide tutorial related to installing and configuring
an Invenio instance and uploading and accessing records.

docs: user guide tutorial

---

docs/usersguide/accessing.rst

* Better examples for accessing multiple formats.

docs: accessing multiple formats

---

docs/community/translation-guide.rst

docs: translation guide

---

docs/usersguide/running.rst
docs/usersguide/tutorial/configure.rst
scripts/instance.cfg

* (closes #3827).
Signed-off-by: Diego Rodriguez <diego.rodriguez@cern.ch>

config: add Celery 4 config variable

---

setup.py

Closes #3862, waiting for invenio-db 1.0.1
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>

installation: bump invenio-db min version to 1.0.1

---

docs/usersguide/index.rst
docs/usersguide/quickstart.rst

docs: rewrite quickstart page

---

invenio/version.py

release: v3.0.0 🚀🎉🎊

---

docs/quickstart.rst
docs/tutorial-module/develop.rst
docs/tutorial-module/index.rst
docs/tutorial-module/run-n-test.rst
docs/tutorial-module/scaffold.rst

This pull request continues where the last one left off. I am updating the Module Tutorial in this one with what I had to do to make the webpage interactions work. I am not too sure if this is what was intended or if the backend is consistent with how things should be. Correct me and don't hesitate to explain things!

Module tutorials scaffold

---

docs/quickstart.rst

* Modifies quickstart guide to work according to the changes in
https://github.com/inveniosoftware/cookiecutter-invenio-instance/pull/67
Addresses https://github.com/inveniosoftware/invenio/issues/3888
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>

docs: quickstart guide with pipenv

---

docs/invenio-modules.rst
docs/tutorial-module/develop.rst
docs/tutorial-module/run-n-test.rst
docs/tutorial-module/scaffold.rst

* Modifies instructions on how to create a new module, and links
guide chapters.
Closes #3884 
Signed-off-by: Dinos Kousidis <dinos.kousidis@cern.ch>

docs: develop a new module guide extension

---

docs/datamodel/build-a-datamodel.rst
docs/index.rst
docs/quickstart/crud-operations.rst

Ready for a first review. There are likely quite some typos 👼 
Please check if it's understandable and if there's things missing or not clear.

docs: build a data model section

---

modules/websearch/lib/search_engine.py

Signed-off-by: Ludmila Marian <ludmila.marian@gmail.com>

WebSearch: improved escaping for warning message

---

invenio/version.py
setup.py

release: 3.1.0.dev20181106

---

MANIFEST.in
docs/quickstart/crud-operations.rst
docs/quickstart/next-steps.rst
docs/quickstart/quickstart.rst
docs/tutorial-module/develop.rst
docs/tutorial-module/first-commit.rst
docs/tutorial-module/run-n-test.rst
docs/tutorials/build-a-datamodel.rst

Docs: update the documentation for cookiecutter

---

docs/conf.py
docs/tutorials/managing-access.rst

Documentation - managing permissions

---

docs/architecture/application.rst
docs/architecture/infrastructure.rst

fix typos and language in application/infrastructure docs.

minor fixes in docs

---

docs/releases/v3.1.0.rst

* Typo on v3.1.0.rst file
Signed-off-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

docs: Typo

---

docs/releases/v3.1.0.rst

A few small typo fixes to the 3.1 release notes.

Fixing typos in release notes

---

docs/conf.py
docs/general/bundles.rst
docs/general/introduction.rst
setup.py

docs: review

---

.travis.yml
docs/architecture/infrastructure.rst
docs/conf.py
docs/general/requirements.rst
setup.py

global: ES7 support

---

docs/quickstart/crud-operations.rst
docs/quickstart/quickstart.rst

docs: quickstart review

---

docs/architecture/infrastructure.rst
docs/files/backends.rst
docs/files/index.rst
docs/files/integration.rst
docs/files/serve.rst
docs/index.rst

[1] docs: files introduction

---

docs/index.rst
docs/managing-files/index.rst
docs/managing-files/previewer.rst

[2] docs: previewer explanation

---

docs/conf.py
docs/managing-files/big_files.rst
docs/managing-files/index.rst
docs/managing-files/integrity.rst

[3]docs: adds integrity check section

---

.travis.yml
docs/tutorials/build-a-repository.rst

``` console
$ git grep production
docs/community/code-of-conduct.rst:      is to find them early, before they make it into production.
docs/deployment/securing-your-instance.rst:  production)
docs/general/bundles.rst:    This bundle is in beta. The modules are being used in production systems
docs/general/bundles.rst:    This bundle is in alpha. The modules are being used in production systems
docs/general/bundles.rst:    These modules are in alpha. The modules are being used in production
docs/general/bundles.rst:which are all being used in production systems, but which are likely subject
docs/migrating.rst:v2.1 production environment, the one we recommend is using `Virtualenv
docs/releases/v0.rst:Invenio v0.x code base was developed and used in production instances …
```

docs: remove production suggestion

---

docs/deployment/securing-your-instance.rst

docs: add CSRF protection documentation

---

docs/releases/index.rst
docs/releases/v3.2.2.rst
invenio/version.py

Release 3.2.2

---

setup.py

* Adds latest module releases with Semantic UI integration.

installation: bump semantic ui alpha versions

---

.travis.yml
docs/general/requirements.rst
docs/index.rst
docs/quickstart/quickstart.rst
docs/releases/index.rst
docs/releases/v3.2.2.rst
docs/releases/v3.3.0.rst
docs/upgrading.rst
docs/upgrading/index.rst
docs/upgrading/upgrade-3_1-3_2.rst
docs/upgrading/upgrade-3_2-3_3.rst
invenio/version.py
setup.py

Migrated from https://github.com/inveniosoftware/invenio/issues/4002
Closes #4017
Closes https://github.com/inveniosoftware/invenio/issues/4008
Closes https://github.com/inveniosoftware/invenio/issues/4011
Closes https://github.com/inveniosoftware/invenio/issues/4010

release v3.3

---

setup.py

* Updates dependencies to latest versions
* Change test dependencies to be managed by pytest-invenio.

installation: update dependencies

---

docs/community/development-environment.rst
run-tests.sh

docs: enhance developer environment docs

---

README.rst
docs/community/_getting-help.rst
docs/community/channels.rst
docs/community/development-environment.rst
docs/community/security-policy.rst

Closes https://github.com/inveniosoftware/opensource/issues/67

docs: change chatroom from gitter to discord

---

CONTRIBUTING.rst
pytest.ini

Review guidelines as used by RDM team members.

contributing: review guidelines

---

invenio/version.py
setup.py

Depends on https://github.com/inveniosoftware/invenio-i18n/pull/94

dependencies: bump i18n and oauthclient

---

docs/releases/upgrading/index.rst
docs/releases/upgrading/upgrade-3_3-3_4.rst

Related to https://github.com/inveniosoftware/cookiecutter-invenio-instance/issues/225

docs: Adds upgrade guide for 3.3 to 3.4

---

docs/getting-started/development-environment.rst

Linux development environment setup

---

setup.py

:heart: Thank you for your contribution!
Please describe briefly your pull request.
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyright-policy.html) for details.
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. …

dependencies: bump invenio-oaiserver
