inveniosoftware/invenio

config/invenio.conf

* Deletes cached `recjson` format immediately after record update, so
that it is not necessary to wait for the next `bibreformat` run for
the record JSON format and the record master format (MARC) to be
fully consistent.  (addresses #1708)

BibUpload: faster recjson deletion after updates

---

modules/webbasket/lib/webbasket_templates.py

* Improves formatting of the delete basket confirmation message by
escaping only necessary parts.  (closes #2449)
Reported-by: Alexander Wagner <alexander.wagner@desy.de>

WebBasket: better formatting of deletion message

---

invenio/legacy/bibupload/engine.py

* Prevents dog-piling behavior when multiple processes call get_record
and no cache exists (i.e. each process will try to generate the
cache and save it).

bibupload: get_record dog-piling prevention

---

invenio/modules/deposit/field_base.py
invenio/modules/deposit/static/js/deposit/form.js
invenio/modules/deposit/testsuite/test_deposit_form.py

* Separates connecting events and initializing typeahead so that
one can set up a custom typeahead with all the events connected
with the form.
Co-authored-by: Kamil Neczaj <kamil.neczaj@cern.ch>

deposit: separation of typeahead initialization

---

invenio/ext/login/__init__.py
invenio/modules/accounts/views/accounts.py
invenio/modules/oauthclient/config.py
invenio/modules/oauthclient/handlers.py
invenio/modules/oauthclient/utils.py
invenio/utils/washers.py

* Sets session.permanent when then user marks 'remember me'.
* Allows configuration of oauth login to set if session should
be permanent.

accounts: fix for permanent login support

---

invenio/legacy/bibconvert/cli.py
invenio/legacy/bibconvert/scripts/bibconvert.py

* Removes traces of BFX engine from command line tools.
(addresses #2124)

BibConvert: BFX engine removal from cli

---

invenio/modules/accounts/models.py
invenio/modules/oauthclient/contrib/orcid.py
invenio/modules/oauthclient/handlers.py
invenio/modules/oauthclient/utils.py

* Uses userEXT table to do a lookup of the external identifier
in order to find the local account corresponding to the user
that logs in using oauth.
Signed-off-by: Javier Martin Montull <javier.martin.montull>

oauthclient: local account discovery improvement

---

invenio/legacy/bibupload/engine.py

* Renames import in order to avoid overriding local variable.
(closes #2665)

legacy: fix import overriding local variable

---

invenio/modules/jsonalchemy/jsonext/functions/to_int.py
invenio/modules/jsonalchemy/testsuite/fields/toint.cfg
invenio/modules/jsonalchemy/testsuite/models/test_toint.cfg
invenio/modules/jsonalchemy/testsuite/test_functions.py

Signed-off-by: Mateusz Susik <mateusz.susik@cern.ch>
When a field is optional in the jsonalchemy record definition file, and it contains an integer, the behaviour when the integer subfield is missing is weird.
``` python
experiments:
"""Contains information about experiments."""
schema:
{'experiments': {'type': 'list', 'force': True, 'items': {
'id': {'type': 'string'},
'start_year': {'type': 'integer', 'nullable': True,
'min': __import__('flask').current_app.config['INSPIRE_YEAR_MIN'],
'max': __import__('flask').current_app.config['INSPIRE_YEAR_MAX']},
'end_year': {'type': 'integer', 'nullable': True,
'min': __import__('flask').current_app.config['INSPIRE_YEAR_MIN'],
'max': __import__('flask').current_app.config['INSPIRE_YEAR_MAX']},
'status': {'type': 'string', 'nullable': True, …
```

jsonalchemy: function for safe conversion to integer

---

invenio/modules/formatter/templates/format/records/recjson.tpl
invenio/modules/jsonalchemy/parser.py
invenio/modules/jsonalchemy/reader.py
invenio/modules/jsonalchemy/testsuite/fields/hidden.cfg
invenio/modules/jsonalchemy/testsuite/models/test_hidden.cfg
invenio/modules/jsonalchemy/testsuite/test_bases.py
invenio/modules/jsonalchemy/testsuite/test_parser.py
invenio/modules/jsonalchemy/wrappers.py

* Adds @hidden decorator for field definition and extends `dumps()`
method with `filter_hidden=False` argument.  (addresses #2197)

jsonalchemy: @hidden decorator addition

---

modules/miscutil/lib/inveniocfg.py

* Disables SSLv2 and SSLv3 in Apache configuration due to known
vulnerabilities.  (closes #2515)
* Adds also SSLCipherSuite directive.
Tested-by: Tibor Simko <tibor.simko@cern.ch>

installation: disable SSLv2/SSLv3 in Apache config

---

invenio/base/utils.py
invenio/ext/logging/__init__.py
invenio/modules/deposit/models.py
invenio/modules/workflows/__init__.py
invenio/modules/workflows/engine.py
invenio/modules/workflows/models.py
invenio/modules/workflows/testsuite/test_workflows.py
invenio/modules/workflows/views/holdingpen.py
invenio/modules/workflows/worker_engine.py

* Fix reference to `completed_objects` in the documentation (was:
`final_objects` in code).
* Expose all other states via the `BibWorkflowEngine` interface and
expand documentation.

workflows: correspond object state names with docs

---

invenio/modules/knowledge/restful.py

* Moves endpoint from /api/knowledges to /api/knowledge.
(#addresses #2686)
* Fixes order of imports.
* Fixes blank except statement.

knowledge: endpoint move

---

invenio/modules/deposit/models.py

* Fixes issue where deleting a single unpublished deposit object
could result in other objects being deleted as well.

deposit: workflow delete fix

---

invenio/modules/deposit/bundles.py

* Locks the bundle version of the library to 3.1.3, because the latest
one (4.0.0) is not working properly (closes #2689).
Signed-off-by: Sebastian Witowski <sebastian.witowski@cern.ch>

deposit: eonasdan-bootstrap-datetimepicker fix

---

modules/miscutil/sql/tabcreate.sql

* Adds missing upgrade recipe from PR #1753 to `tabcreate.sql`, which
makes that all upgrade recipes are listed there now.

installation: all upgrade recipes in tabcreate

---

setup.py

* Downgrades the httpretty version in requirements to
fix urllib3 version conflicts.

installation: httpretty<=0.8.0 version limit

---

invenio/modules/oauthclient/config.py
invenio/modules/oauthclient/contrib/orcid.py
invenio/modules/oauthclient/handlers.py
invenio/modules/oauthclient/testsuite/test_forms.py
invenio/modules/oauthclient/testsuite/test_views.py
invenio/modules/oauthclient/views/client.py
invenio/utils/url.py

* Fixes a CSRF issue in oauthclient in which the next parameter to
"/oauth/login/app/?next=" could be used by an attacker to redirect
the end-user to an external URL.
* Adds use of OAuth 2.0 state parameter for all oauthclients for
further CSRF protection.
Reported-by: rcpeters <info@rcpeters.com>

oauthclient: cross-site request forgery fix

---

invenio/modules/formatter/format_elements/bfe_date.py
invenio/modules/formatter/format_elements/bfe_imprint.py
invenio/modules/formatter/format_elements/bfe_meta.py

* Uses `strftime` and `strptime` from `invenio.utils.date`
instead of these from Standard Library.

formatter: support for dates < 1900

---

Makefile.am

* Updates location from where to download MathJax tarball to the one
hosted on invenio-software.org.  (closes #2732)

installation: MathJax distribution location update

---

setup.py

* Adds minimum version requirement on Pillow due to DOS vulnerability
in previous version (see CVE-2014-9601).

installation: Pillow minimum version

---

modules/bibindex/lib/bibindex_regression_tests.py
modules/pdfchecker/lib/arxiv_pdf_checker_regression_tests.py

* Fixes test suite's handling of record original modification dates that
was causing troubles on a Debian 6 installation using Python-2.6,
MySQL-5.1, MySQLdb-1.2.4.  (closes #2737)

global: test suite original modification date fix

---

invenio/modules/previewer/static/js/previewer/pdfjs/fullscreen.js
invenio/modules/previewer/templates/previewer/zip_base.html

* Identifies folder by id of the tree elment. (closes #2748)
* Adds fullscreen mode.
* Expands all elements by default. (closes zenodo/zenodo#157)

previewer: zip previewer enhancements

---

invenio/legacy/bibindex/engine.py

* Fixes an SQL query that was ambiguos according to MariaDB 5.5.

indexer: SQL query fix

---

invenio/modules/accounts/templates/accounts/login_base.html

* Allows child templates to override the title of the login
page.

accounts: login template allow set title

---

invenio/celery/utils.py
invenio/legacy/miscutil/dbdump.py

Allows to use the `--disable-workers` flag to also suspend Celery tasks during db dumps.
Expect a lot of PEP8 errors on dbdump.py (did not fix them as I dunno if there will be more patches coming from master).
@jmartinm @kaplun

dbdump: disable workers

---

invenio/base/templates/page_base.html

* Creates an extra block trackingcode to allow addition of
tracking JavaScript like Piwik without conflicting with the
usage of JavaScript block in other modules.

base: page template block addition

---

Dockerfile
docker-compose.yml

* Switches to local Redis so that Invenio demo site image is fully built
when standalone.
* Switches to sendmail MTA which makes all unit tests to pass.
* Installs LibreOffice prerequisite which makes all regression tests to
pass.  (when run second time)

docker: more complete configuration

---

AUTHORS

* Completes the list of past authors with people that did not explicitly
appear as the CVS commit authors.  (From pre-Git times.)  Names taken
from the old format of the AUTHORS file.

docs: more complete list of past authors

---

invenio/modules/oauthclient/config.py
invenio/modules/oauthclient/contrib/orcid.py
invenio/modules/oauthclient/handlers.py
invenio/modules/oauthclient/testsuite/fixture.py
invenio/modules/oauthclient/testsuite/test_contrib_orcid.py
invenio/modules/oauthclient/utils.py
invenio/modules/oauthclient/views/client.py

* Adds tests for ORCID client.
* Fixes issue with ORCID client not properly cleaning up UserEXT.
* Fixes issue with ORCID client not properly creating UserEXT links
when user is already logged in.
* Fixes undefined variable issue.
* Fixes flashing of message when user rejects requests.
* Fixes ORCID API endpoint.
* Changes request library to use Flask-OAuthlib internal.
* NOTE Changes method signature of account_setup handler to take 3
arguments instead of 2. DeprecationWarnings are issued for
existing account_setup methods.
* NOTE Supersedes PR #2712
Test coverage:
```
Name                                         Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------- …
```

oauthclient: orcid login fix + tests

---

setup.py

* Adds missing anyjson and amqp packages.
Signed-off-by: Wojciech Ziolek <wojciech.ziolek@cern.ch>

installation: RabbitMQ and anyjson requirements

---

invenio/modules/submit/__init__.py
invenio/modules/submit/models.py
invenio/modules/submit/upgrades/__init__.py
invenio/modules/submit/upgrades/submit_2015_03_03_fix_models.py

* Fixes id_father foreign keys to support Null value.
* Removes invalid default values.
* PEP8/257 fixes.

submit: fix foreign keys definition in models

---

invenio/modules/search/views/search.py

* FIX Generates correct url for `/collection` redirect.

search: fix broken collection redirect

---

modules/miscutil/lib/testutils.py

* FIX Switches off SSL verification when running the test suite.  Useful
for Python-2.7.9 where self-signed SSL certificates (that are usually
used on development installations) would cause apparent test
failures.  (closes #2868)

testutils: no SSL verification for Python-2.7.9

---

setup.py

* Expands project description in place of "Invenio is Fun".
* Adds `tests` target to `extras_require` so that developers could
install test-related dependencies via `pip install -e .[tests]`.
* Improves PEP-8 compliance and code kwalitee.

installation: better description and pip tests target

---

INSTALL
modules/bibharvest/web/test_insert_oai_source.html
modules/bibmatch/lib/bibmatch_regression_tests.py
modules/miscutil/lib/__init__.py
modules/websearch/lib/websearch_external_collections_config.py

* FIX Replaces `invenio-demo.cern.ch` by `demo.invenio-software.org`
which is the new canonical URL of the demo site.  (addresses #2867)

global: canonical demo.invenio-software.org URL

---

invenio/modules/upgrader/commands.py

* Clarifies that the upgrade dependency is only a best guess.
(closes #2561)

upgrader: documentation fix

---

setup.py

* FIX Reorders 'compile_catalog' and 'install' commands to fix installation process from PyPI.

installation: compile catalog and install recorder

---

modules/miscutil/lib/upgrades/invenio_2012_11_15_bibdocfile_model.py

* Uses the get() method instead of __getitem__() defaulting the return
value to an empty dictionary in case of missing keys in more_info.

BibDocFile: safer new bibdocfile model upgrade

---

invenio/base/static/js/settings.js
invenio/modules/messages/bundles.py

* FIX Sets a defined version to use for jQuery-Timepicker-Addon instead
of automatically use latest.
* FIX Defines a path for jquery.ui required by jQuery-Timepicker-Addon.
(closes #2910)

messages: jQuery-Timepicker-Addon fix

---

INSTALL.rst
RELEASE-NOTES
RELEASE-NOTES.rst
invenio/version.py

* Increases version number after the release of Invenio v2.0.1.
* Adds note about `pip install babel` that is still necessary to do
before installing Invenio from PyPI.

installation: post-release version bump

---

INSTALL.rst
RELEASE-NOTES
RELEASE-NOTES.rst
setup.py

* FIX Adds Babel as setup requirements for installing compile_catalog
command.

installation: Babel required in package setup

---

modules/miscutil/lib/inveniocfg.py

* BETTER Apache virtual environments are now created with appropriate
`WSGIPythonHome` directive so that it would be easier to run Invenio
from within Python virtual environments.

installation: Python path in Apache virtual hosts

---

requirements-extras.txt

* FIX Releases constraint on using an old version of `h5py` that was
anyway no longer available on PyPI.
* Also moves `cython` before `h5py` so that `h5py` can be compiled.

installation: latest h5py version

---

invenio/ext/assets/extensions.py

* FIX Implements `__deepcopy__` method for `webassets.filter.option` in
order to fix unexpected behavior of the `option` class contructor.
(addresses #2777) (fixes #2864) (closes #2921)
Reviewed-by: Javier Martin <javier.martin.montull@cern.ch>

assets: fix deepcopy of webassets.filter.options

---

invenio/base/templates/page_base.html

* NEW Adds 'noscript' block to the page template to warn users with
disabled JavaScript on their browser.  (closes #1039)

global: noscript warning addition

---

invenio/ext/assets/extensions.py

* NOTE Adds deprecation warning when LESS_RUN_IN_DEBUG is used.
(addresses #2923)

assets: deprecated LESS_RUN_IN_DEBUG

---

invenio/modules/formatter/registry.py
invenio/modules/search/templates/search/results_base.html

* BETTER Improves support for translated output format names on search
results page.  (closes #2429)

formatter: translated output format names

---

modules/miscutil/lib/inveniocfg.py

* BETTER Apache virtual environments are now created with appropriate
`WSGIDaemonProcess` user value, taken from the configuration variable
`CFG_BIBSCHED_PROCESS_USER`, provided it is set.  This change makes it
easier to run Invenio under non-Apache user identity.

installation: WSGI user in Apache virtual hosts

---

invenio/base/bundles.py
invenio/base/static/js/admin.js
invenio/base/static/js/settings.js
invenio/base/templates/admin_base.html

* FIX Adds `admin.js` bundle that loads `select2.js` library on `/admin`
pages.  (closes #2690) (closes #2781)

admin: fix select2 by adding bundle

---

invenio/ext/jinja2hacks.py
invenio/ext/template/__init__.py

* NOTE Adds deprecation warning for `invenio.ext.jinja2hacks` and all detected non-ascii strings usage in templates mainly coming from legacy (1.x) modules.  (addresses #2862)
Reviewed-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

global: jinja2hacks deprecation and usage warning

---

invenio/modules/documents/documentext/fields/base.cfg

As discussed on Hangouts/Gitter, running `nosetests invenio/modules/documents/testsuite/test_api.py` is currently broken due to a broken import in `invenio/modules/documents/documentext/fields/base.cfg`, similar to https://github.com/inveniosoftware/invenio/commit/0875c0570b99f77af5a715ed35857c506b6e8bbf.

documents: fix Flask-Login import

---

invenio/modules/search/static/js/search/form.js

* Hotfixes loading of typeahead.js library.  (closes #2559)

search: hotfix form typeahead loading

---

invenio/base/templates/invenio-apache-vhost.tpl

* FIX Adds rewrite rule in Apache site configuration to avoid problems
with loading '/admin' url without trailing slash that attempts to
serve the static directory of the same name.  (closes #2470)
* NOTE Recreate Apache site configurations using new template.
Run following command `inveniomanage apache create-config`.
--
@dset0x  I have backported your commit (094b603971a3331b993b215a861772a204f1ad38).

base: url rewrite rule for '/admin' to '/admin/'

---

invenio/utils/remote_debugger/__init__.py

* NOTE Deprecates custom remote debuggers. Please use native Werkzeug
debugger or other (*)pdb equivalents.  (addresses #2945)

global: deprecation of custom remote debugger

---

invenio/modules/authors/recordext/fields/author_base.cfg
invenio/modules/jsonalchemy/testsuite/fields/authors.cfg
invenio/modules/jsonalchemy/testsuite/fields/fields.cfg
invenio/modules/jsonalchemy/testsuite/fields/oldvalue.cfg
invenio/modules/records/testsuite/fields/atlantis.cfg
invenio/modules/uploader/recordext/fields/files.cfg
invenio/testsuite/data/test_authors.cfg

* Introduces support for accepting MARC fields having any indicator
(closes #1722)
* Fixes the definition of time_and_place_of_event_note,
series_statement and source_of_description fields.
Reported-by: Ferran Jorba <Ferran.Jorba@uab.cat>

JSONAlchemy: any indicator support

---

invenio/modules/indexer/models.py
invenio/modules/search/searchext/engines/native.py
invenio/modules/search/searchext/units/author.py
invenio/modules/search/searchext/units/authorityauthor.py
invenio/modules/search/searchext/units/exactauthor.py
invenio/modules/search/searchext/units/exactfirstauthor.py
invenio/modules/search/searchext/units/firstauthor.py
invenio/modules/search/searchext/units/subject.py
invenio/modules/search/utils.py
invenio/modules/search/walkers/search_unit.py

Here is a bundle of fixes to the new search structure I did with @jirikuncar 
Basically it fixes the default author search to return the correct result if you only search for the lastname (as one word), and that records without any collections do not display in search results.

search: author search and collection results

---

invenio/legacy/bibsort/engine.py

* FIX Comparison function of record tags uses space concatened string from list of all tags values.  (addresses #2750)

sorter: fix locale based comparison of lists

---

invenio/base/templates/invenio-apache-vhost.tpl

* FIX Drops support for serving directories in Apache site configuration
to avoid problems with loading '/admin' url without trailing slash
that attempts to serve the static directory of the same name. (closes
#2470) (invalidates #2943)
* NOTE Recreate Apache site configurations using new template.
Run following command: `inveniomanage apache create-config`.
---
This is awaiting to be tested on some `maint` flavor.
Critical fix. #2943 breaks all static files. (at least on `master` it does.)

base: url rewrite not to serve directories

---

invenio/legacy/external_authentication/__init__.py

* NOTE External authentication methods are being deprecated. Please use
`invenio.modules.oauthclient` or Flask-SSO instead.  (addresses #1083)

global: deprecation of external authentication

---

invenio/modules/knowledge/api.py

* Relaxes constrictions on dynamic search function that
force us to create temporary knowledge.
(closes #698)

knowledge: temporary knowledge creation removal

---

docs/developers/git-workflow.rst

* NEW Documents commit message labels for automatic generation of
release notes.  (closes #2856)

docs: commit message labels

---

.travis.yml

* FIX Fixes TypeError error on markupsafe library. (closes #2862)

travis: unittest2 requirements fix

---

docs/contents.rst.inc
docs/deprecationpolicy.rst
invenio/utils/deprecation.py

Some features that have barely been used may require significant effort to deprecate. The proposal is to allow getting rid of them faster.
Allow fast track feature deprecation (i.e. removed in current version +0.1 instead of current version +0.2) for **poorly tested, non-core and little used features for which alternatives already exists**. E.g. the remote debugging feature (#2945) was basically not used, untested, and the werkzeug debugger already does nearly the same.

RFC fast track deprecation policy

---

invenio/legacy/search_engine/__init__.py

* Removes wrong argument from `rank_records` call.  (closes #2884)

search: fix arguments passed to rank_records

---

invenio/base/scripts/config.py

Adds a command to request the location of the instance config file. Proper error handling (message + return code) is implemented in case the config file does not exist.
Rebased against: `maint-2.0`
Replacement for: #2989
Prepares: #2986

global: new `inveniomanage config locate` command

---

invenio/legacy/bibindex/engine_washer.py
invenio/modules/indexer/testsuite/test_indexer_engine.py
invenio/modules/indexer/testsuite/test_indexer_engine_washer.py
invenio/modules/indexer/tokenizers/BibIndexCJKTokenizer.py

* FIX Avoids an exception from happening when passing a unicode string
to the BibIndex engine washer. (closes #2981)
* Adds a unit test to cover this case.
Co-authored-by: Eamonn Maguire <eamonn.maguire@cern.ch>

indexer: fix for term washing

---

invenio/base/bundles.py
invenio/ext/jasmine/bundles.py
invenio/modules/accounts/bundles.py
invenio/modules/annotations/bundles.py
invenio/modules/comments/bundles.py
invenio/modules/communities/bundles.py
invenio/modules/deposit/bundles.py
invenio/modules/editor/bundles.py
invenio/modules/formatter/bundles.py
invenio/modules/groups/bundles.py
invenio/modules/messages/bundles.py
invenio/modules/previewer/bundles.py
invenio/modules/records/bundles.py
invenio/modules/search/bundles.py
invenio/modules/tags/bundles.py
invenio/modules/workflows/bundles.py

* Forces unicode literals on all bundles. (addresses #2967)

global: unicode literals for bundles

---

invenio/base/factory.py

* Checks that a config value is actually found in order to not
output nonsense.
* Reorganizes imports.

base: remove nonsense debug output

---

docs/getting-started/overlay.rst
invenio/base/bundles.py
invenio/base/templates/base/bundles_base.html
invenio/ext/assets/extensions.py

* INCOMPATIBILITY Removes support for runtime compiling of less files in
debug mode when option LESS_RUN_IN_DEBUG is enabled.  (addresses #2923)
Co-authored-by: Jiri Kuncar <jiri.kuncar@cern.ch>

assets: removal of LESS_RUN_IN_DEBUG support

---

invenio/modules/formatter/engine.py

* NOTE Fallback template rendering has been removed and standard
exception logging is in place.  (addresses #2958)

formatter: exception fallback removal

---

invenio/legacy/search_engine/__init__.py

* Fixes issue with the permitted restricted collections not being
pre-cached for guest users (addresses zenodo/zenodo#116).
IMPORTANT: Cannot be merged directly to master, and maybe the fix is not needed on master due to refactoring of search.

legacy: guest user restricted collections fix

---

.kwalitee.yml
invenio/celery/config.py

SECURITY Forces Celery to only accept msgpack content when using standard configuration. This disallows pickle messages which can be used for remote code execution. (closes #3003)
I didn't write extra documentation as mentioned in #3003, because our standard configuration is secure now and you deliberately change the configuration to something insecure now. If you select `pickle` as your config then it's clearly your fault.
Rebased against: `maint-2.0`

celery: only accept msgpack content

---

invenio/modules/communities/templates/communities/index_base.html

* Shows search box with icon and input only
on mobile devices (closes zenodo/zenodo#208).

communities: hidden search box on mobile fix

---

invenio/modules/previewer/views.py

* Extracts only the file extension in case
of multiple dots in one file. (closes zenodo/zenodo#205)

previewer: proper files extension resolution

---

modules/miscutil/lib/upgrades/invenio_2015_04_15_collection_names_with_slashes.py
modules/websearch/lib/websearch_webcoll.py

* FIX Collection names containing slashes are now supported again.
However we recommend not to use slashes in collection names; if
slashes were wanted for aesthetic reasons, they can be added in
visible collection translations.  (closes #2902)
* Adds upgrade recipe to check collection names for slashes and warn the
user about them.  (Soft warning only, since names-with-slashes will
work more or less fine as of this patch.)

WebSearch: fix for collection names with slashes

---

invenio/modules/search/static/css/search/searchbar.css

* FIX Fixes portalbox text overflow and fixes a syntax error.
(closes #3023)
* Adds collections as qualified component for kwalitee.

search: portalbox text overflow fix

---

invenio/legacy/bibindex/engine_stopwords.py

* Makes lazy loading of `stopwords_kb` variable to avoid file parsing
during script loading.  (addresses #1462)

legacy: lazy stopwords knowledge base

---

requirements-devel.txt

* Fixes the repository url of Flask-Admin because it moves from
mrjoes/flask-admin to flask-admin/flask-admin. (closes #3049)

installation: Flask-Admin git url fix

---

.kwalitee.yml

* Excludes legacy code from kwalitee checks. (closes #3022)

global: legacy code exclusion from kwalitee checks

---

.kwalitee.yml
invenio/modules/indexer/admin.py
setup.py

* Uses wtforms_sqlalchemy instead of wtforms.ext.sqlalchemy deprecated
extension. (closes #2620)

indexer: deprecated WTForms extension removal

---

invenio/legacy/bibmatch/validator.py

* Fixes unicode conversion required to use the levenshtein_distance
function. (addesses #3047)

matcher: fix argument types in jaro_fctn

---

invenio/base/i18n.py

* Removes a old hack for Invenio 1.x that loads utf-8 version of the
list of languages instead of unicode. (addresses #2967)

i18n: lang configuration hack removal

---

docs/getting-started/overlay.rst

The list at http://invenio.readthedocs.org/en/latest/getting-started/first-steps.html also includes `subversion`. Is that needed?

docs: fix missing dependencies

---

docs/getting-started/overlay.rst

* FIX Missing 'git+' prefix for pip install
* Rewords slightly to clarify difference between installing
from PyPI and GitHub
Signed-off-by: Dan Michael O. Heggø <danmichaelo@gmail.com>

docs: fix missing git prefix for pip install

---

modules/websession/lib/session.py
modules/webstyle/lib/webinterface_handler_wsgi_utils.py

* SECURITY Adds back the `HttpOnly` cookie attribute in order to better
protect against potential XSS vulnerabilities.  (closes #3064)

WebStyle: HttpOnly cookie attribute

---

invenio/ext/sqlalchemy/__init__.py

* Re-enables VARBINARY for PostgreSQL and resolve a name binding
conflict. (closes #3066)

sqlalchemy: re-enable VARBINARY for PostgreSQL

---

invenio/legacy/refextract/api.py
invenio/legacy/refextract/config.py

Still needs testing and reviews.
* Replaces urllib by requests.
* Saves the file locally using tempfile.
* Removes the file afterwards.
* Fixes indentation, imports and pep8 stuff.

refextract: requests library usage and code style improvements

---

.travis.yml

* Enables cache configuration on travis for apt and pip packages.

travis: apt and pip cache activation

---

invenio/ext/email/__init__.py

* FIX Fixes reference to CFG_SITE_ADMIN_EMAIL (not a global).
Signed-off-by: Dan Michael O. Heggø <danmichaelo@gmail.com>

email: fix reference to CFG_SITE_ADMIN_EMAIL

---

invenio/modules/access/bases.py
invenio/modules/access/testsuite/test_document_restrictions.py

* NEW Adds the ability to restrict access per object independently from
the parent.
Reviewed-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>
Signed-off-by: Harris Tzovanakis <me@drjova.com>

access: restrict access per object

---

invenio/modules/deposit/templates/deposit/completed_base.html
scripts/docker_devboot.sh

A "catch them all" PR to fix some problems I have found while playing around with our demosite. They are rebased against `main-2.0`. The `deposit: leftover cleanup` seems to be critical for the 2.1 release, because without it the affected template will produce an exception at master (= will be 2.1).

misc: problems with deposit, problems with docker

---

invenio/legacy/dbquery_mysql.py

* Fixes imports on dbquery legacy interface. (addresses #3089)

legacy: dbquery import fix

---

invenio/legacy/bibdocfile/cli.py

* Fixes MySQL ansi_quote problem for bibdocfile run_sql.
(addresses #3089)

legacy: fix run_sql ansi quotes in bibdocfile

---

invenio/legacy/oaiharvest/admin.py

* Strips the input of certain fields when adding and editing
OAI harvest source configurations.

legacy: OAI Harvest admin input stripping

---

INSTALL.rst

* Add a step describing how to install mysql on CentOS 7 because it
does not have mysql-server package by default.

installation: fix mysql install steps for CentOS 7

---

invenio/base/wrappers.py
invenio/ext/confighacks.py

* INCOMPATIBLE Changes url_for behaviour to return always a unicode
string. (addresses #2967)
* INCOMPATIBLE Deprecates invenio.config hack for legacy code.
(addresses #3106)

global: url_for unicode compatibility fix

---

invenio/base/config.py
invenio/base/scripts/config.py
invenio/base/scripts/demosite.py
invenio/base/utils.py
invenio/ext/legacy/__init__.py
invenio/ext/logging/__init__.py
invenio/legacy/batchuploader/cli.py
invenio/legacy/batchuploader/engine.py
invenio/legacy/bibsched/bibtask.py
invenio/legacy/bibsched/cli.py
invenio/legacy/ckeditor/connector.py
invenio/legacy/webbasket/webinterface.py
invenio/legacy/webcomment/webinterface.py
invenio/legacy/webdoc/api.py
invenio/legacy/websession/inveniogc.py
invenio/legacy/websubmit/admincli.py
invenio/legacy/websubmit/functions/Move_CKEditor_Files_to_Storage.py
invenio/legacy/websubmit/webinterface.py
invenio/modules/comments/api.py
invenio/modules/workflows/models.py
invenio/testsuite/test_legacy_docextract_convert_journals.py
invenio/testsuite/test_manage.py
invenio/utils/deprecation.py

* Replaces custom path concatenations with `os.path.join`
* Refactors commonly used paths to use config variables.
* ~~Renames `CFG_PREFIX` to `_CFG_PREFIX`.~~ updated by @jirikuncar
---
I would like some input on this in order to drop the WIP tag quicker:
Some references to `_CFG_PREFIX` remain and perhaps some `legacy/` files were better off remaining similar to their `master` equivalents.
If accepted, supersedes  #2818

global: refactored `CFG` variables

---

modules/websession/lib/session.py

* Adds HttpOnly attribute to stub cookies as well.  (addresses #3064)
Reviewed-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

WebSession: HttpOnly attribute in stub cookies

---

modules/websearch/lib/search_engine.py

* FIX Removes special behaviour of the "subject" index that was
hard-coded based on the index name.  Installations should rather
specify wanted behaviour by means of configurable tokeniser instead.
Reviewed-by: Jan Aage Lavik <jan.age.lavik@cern.ch>

WebSearch: no special behaviour for subject index

---

invenio/modules/records/api.py

* FIX Improves type consistency of keys and values in JSON record
created from MARC and retrieved from storage engine.  (closes #2772)

records: fix type consistency of record

---

invenio/base/scripts/database.py

* BETTER Adds default priviledges for database user to access from any
host.
--
cc @hachreak @crepererum 
PS: It's going to `maint-2.0`.

installation: database init for any host

---

invenio/ext/sqlalchemy/__init__.py
invenio/modules/oauth2server/models.py
invenio/modules/oauth2server/upgrades/oauth2server_2014_02_17_initial.py

* Modifies imports to directly import the types required.
(addresses #3163) (addresses kvesteri/sqlalchemy-utils#145)

global: refactoring import from sqlalchemy_utils

---

invenio/modules/collections/upgrades/collections_2015_05_28_recjson_tag_value.py

* NOTE Check that 'tag' table contains 'collection idetifier' with
correct 'value' and 'recjson_value' ('' and '_collections').

collections: upgrade recipe for tag table

---

invenio/ext/sqlalchemy/utils.py

* Adds missing access rights for database user accessing server from
localhost.  (closes #3146)

installation: grant db access on localhost

---

invenio/modules/oauthclient/handlers.py
invenio/modules/oauthclient/testsuite/test_contrib_orcid.py
invenio/modules/oauthclient/utils.py

* FIX users creating their account with oauth process have to validate
their email too. Previously it was marked as valid from the start.
* FIX a validation email is now sent when users create their account
with oauth and their email address is not provided by the oauth
service. (closes #2739)

oauthclient: validate oauth users' email

---

invenio/ext/login/legacy_user.py
invenio/modules/access/local_config.py
invenio/modules/deposit/acl.py
invenio/modules/deposit/cache.py
invenio/modules/deposit/models.py
invenio/modules/deposit/restful.py
invenio/modules/deposit/testsuite/test_type_simplerecord.py
invenio/modules/deposit/views/deposit.py

* NEW Adds usedeposit action which enables per user access
restrictions for different deposit types.  (closes #2724)
* Requires running `webaccessadmin -u admin -c -a -D` command.
Signed-off-by: Jan Stypka <jan.stypka@cern.ch>

access: usedeposit action addition

---

invenio/modules/documents/utils.py
invenio/modules/records/views.py

* NOTE Ports basic BibDocFile serving including access right checks.
(closes #3160)
--
This commit brings back only limited support for BibDocFile serving. Do you have any critical use-cases that are missing?
cc @lnielsen @tiborsimko @egabancho @kaplun

records: port of BibDocFile serving

---

invenio/legacy/dbquery_mysql.py

* FIX Catches also any `MySQLdb.OperationalError` coming from legacy
MySQL queries using `run_sql()`. (addresses #3089)
As promised in https://github.com/inveniosoftware/invenio/issues/3089#issuecomment-106484781

legacy: dbquery exception handling

---

invenio/legacy/oairepository/server.py
invenio/legacy/search_engine/__init__.py
invenio/modules/collections/recordext/functions/get_record_collections.py
invenio/modules/formatter/template_context_functions/tfn_get_fulltext_snippets.py
invenio/modules/records/utils.py
invenio/modules/search/api.py
invenio/modules/search/views/search.py

* Renames SearchEngine class to Query that better describes its
function.
* NEW Adds new API for querying records.
* INCOMPATIBLE Removes support for legacy `perform_request_search` and
`search_unit` API functions.
Reviewed-by: Tibor Simko <tibor.simko@cern.ch>

search: new Query class

---

invenio/ext/passlib/hash.py
invenio/modules/accounts/upgrades/accounts_2015_03_06_passlib.py
invenio/testsuite/test_ext_passlib.py

* Fixes passlib upgrade recipe introduced in 2d4a028 to
properly handle users with empty string as password. (closes #3070)
* Fixes issue with handling of unicode values.

accounts: passlib empty password fix

---

invenio/modules/access/config.py
invenio/modules/access/control.py

* FIX Sets the superadmin role ID properly when elaborating access
authorizations. Previously it was masked behind an application
context exception. (closes #3184)
* NOTE The default access role ID for the superadmin user is 1, but
it can be configured via CFG_SUPERADMINROLE_ID.
* Removes a double wrong quote in `acc_find_possible_actions()`.

access: superadmin role fix

---

invenio/ext/jinja2hacks.py

* BETTER Changes the hacks to only triggers warnings from non-unicode
strings in jinja templates when in DEBUG mode to avoid taking a
performance hit in production. This is important until the data model
is only represented in Unicode.
CC @lnielsen

jinja2hacks: only warnings in DEBUG mode

---

INSTALL.rst
NEWS
README.rst
RELEASE-NOTES
RELEASE-NOTES.rst
invenio/version.py

- 5c102715e8c3424fd602a1ee27c87f380335861e Invenio v2.0.4
- c9dbe0613e31595a643dd362ab23270601da6ac1 knowledge: fix HTML character encoding
- e09e314123d6aaa43e88106eabc115401939a05e installation: Apache 2.4 configuration syntax fix
Notes:
- autogenerated release notes may have some sections coming for the legacy modules that are not exactly applicable to 2.0.  (session cookies)  May need to amend this perhaps...
- changing s/choosing/flying/ as done in maint-1.x branches
- changing reST formatting of NEWS file as done in maint-1.x branches

Invenio v2.0.4

---

invenio/legacy/dbquery_mysql.py

* FIX Sets the ANSI_QUOTES setting also on the second attempt
to connect to the database in case of a lost connection.

legacy: ANSI_QUOTES setting on second try

---

invenio/legacy/search_engine/__init__.py

* FIX Fixes a broken import in the `print_record()` function
of search_engine.

legacy: print_record import fix

---

docs/developers/docker.rst

* Adds documentation for boot2docker. (closes #3194)

docker: boot2docker documentation

---

invenio/legacy/__init__.py
invenio/legacy/bibcirculation/__init__.py
invenio/legacy/bibdocfile/__init__.py
invenio/legacy/bibedit/__init__.py
invenio/legacy/elmsubmit/__init__.py
invenio/legacy/websearch_external_collections/__init__.py
invenio/legacy/websubmit/__init__.py

* INCOMPATIBLE Specifies deprecation warnings for legacy modules
bibcirculation, bibdocfile, bibedit, elmsubmit,
websearch_external_collections, and websubmit.

legacy: deprecation warnings addition

---

invenio/ext/login/__init__.py
invenio/modules/oauthclient/contrib/cern.py

* NEW Adds support for CERN authentication.  (PR #2821)
Co-authored-by: Pamfilos Fokianos <pamfilos.fokianos@cern.ch>

oauthclient: support for CERN authentication

---

invenio/modules/workflows/models.py
invenio/utils/plotextractor/cli.py

* Fixes CFG_TMPSHAREDDIR variable's name.
* Fixes direct_xml_output varible definition. (closes #3221)

global: fix CFG_TMPSHAREDDIR variable name

---

invenio/legacy/websession/inveniogc.py

* FIX Fixes inveniogc crash when mysql is NOT used to store sessions.
(closes #3205)

legacy: fix of inveniogc when using redis sessions

---

invenio/modules/documents/utils.py

* BETTER Improves support in filenames with dashes `-` on legacy
`BibDocFile`.
Signed-off-by: Harris Tzovanakis <me@drjova.com>

documents: improve legacy filename handling

---

.editorconfig

* Reverts change that was accidentally done by mistake in 0c9ffff.
Rebased against: `main-2.0`
See https://github.com/inveniosoftware/cookiecutter-invenio-module/pull/13

global: editorconfig fix

---

invenio/modules/oauthclient/contrib/cern.py

* Fixes wrong code example in setup documentation for the CERN
oauthclient.

oauthclient: cern documentation fix

---

invenio/ext/legacy/__init__.py
invenio/modules/accounts/fixtures.py

* NOTE Moves admin user creation from legacy extension to accounts
fixture. It resolves a problem with next value of the serial id
on PostgreSQL. (closes #3216)

accounts: admin user fixture addition

---

invenio/modules/access/models.py
invenio/modules/access/testsuite/test_cookie.py

* Fixes mail cookie check.
* Adds a testsuite for mail cookie.

access: fix mail cookie check

---

invenio/modules/oauth2server/models.py
invenio/modules/oauth2server/testsuite/test_models.py
invenio/modules/oauth2server/testsuite/test_provider.py

* Sets user_id nullable on Client and Token tables.
* Fixes testsuite to completely clean database records after tests are
finished. (closes #3145)

oauth2server: fix PostgreSQL compatibility

---

invenio/modules/workflows/engine.py
invenio/modules/workflows/models.py
invenio/modules/workflows/testsuite/test_workflows.py
invenio/modules/workflows/testsuite/test_workflows_delayed.py
invenio/modules/workflows/testsuite/test_workflows_model.py
invenio/modules/workflows/testsuite/test_workflows_others.py
invenio/modules/workflows/upgrades/workflows_2015_06_05_resize_uuid_columns.py

* Fixes UUID usage on bwlWORKFLOW, bwlWORKFLOWLOGGING tables.
(closes #3217)
* Defines a delete cascade action for BibWorkflowObject and
BibWorkflowObjectLog if you delete a Workflow.
* Fixes testsuite to properly clean the database after ending.
(closes #3147)

workflows: fix PostgreSQL model compatibility

---

invenio/modules/accounts/forms.py

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

accounts: fix typo in `repeat_email_validator`

---

invenio/modules/accounts/forms.py
invenio/modules/accounts/helpers.py

* BETTER When contacting users, use the localized site name.
(addresses #3273)

accounts: localized site name for user email

---

invenio/modules/workflows/models.py
invenio/modules/workflows/upgrades/workflows_2015_06_05_resize_uuid_columns.py

* Uses of strings to represent workflow uuid. (closes #3288)
* Adds casting to string when someone set a uuid.

workflows: partial undo of e8f6551

---

invenio/ext/sqlalchemy/__init__.py

A `LocalProxy`ed string can't be passed as an argument to a SQL query when using PostgreSQL: the type is probably checked before substitution/sanitization.
I'd expect that this is happening in many more places.

access: fix PostgreSQL compatibility

---

invenio/modules/access/admin_lib.py
invenio/modules/access/control.py
invenio/modules/access/firerole.py
invenio/modules/access/models.py

* Fixes sql queries to improve standard compliance and compatibility:
"RLIKE", quoting. (addresses #3214)
* Fixes problem of assignement of -1 to a foreign key, removing foreign
key and shaping relationship to exclude -1 value. (closes #3099)

access: fix foreign key declaration

---

invenio/modules/access/control.py

* FIX Fixes the authorization delete query to consider NULL value
on id_accARGUMENT authorization column.
The using of NULL value in substitution of zero value was introduced
in the commit 7974188 because Foreign Key don't support it.

access: fix update allowedkeywords on action

---

invenio/modules/access/upgrades/access_2015_06_25_id_accARGUMENT_from_zero_to_null.py

* Replaces all zero values with NULL.
The using of NULL value in substitution of zero value was introduced
in the commit 7974188 because Foreign Key don't support it.

access: id_accARGUMENT zero replacement

---

invenio/ext/sqlalchemy/types/legacyinteger.py
invenio/modules/access/testsuite/test_cookie.py

* Fixes cookie creation with PostgreSQL. (closes #3318)

access: fix cookie creation with PostgreSQL

---

invenio/modules/search/api.py

* Fixes an exception when calling `Results.recids`. (closes #3335)

search: response recids fix

---

invenio/ext/sqlalchemy/__init__.py
invenio/modules/access/control.py
invenio/modules/collections/models.py
invenio/modules/collections/upgrades/collections_2015_07_14_innodb.py
invenio/modules/knowledge/models.py
invenio/modules/knowledge/upgrades/knowledge_2015_07_14_innodb.py
invenio/modules/oaiharvester/models.py
invenio/modules/oaiharvester/upgrades/oaiharvester_2015_07_14_innodb.py
invenio/modules/oauth2server/models.py
invenio/modules/oauth2server/upgrades/oauth2server_2015_07_14_innodb.py
invenio/modules/oauthclient/testsuite/test_models.py
invenio/modules/upgrader/upgrades/invenio_2015_07_14_innodb.py

* INCOMPATIBLE Sets default MySQL storage engine to `InnoDB` (was
`MyISAM`).
* Fixes models that have invalid foreign key types (affects
collections, knowledge, oaiharvester, oauth2server).
* Fixes bug in access rule creation, caused by the fact that Python
evaluates `0` to `False`.

global: InnoDB for MySQL

---

invenio/ext/es.py

* FIX Fixes elasticsearch indexing by disabling automatic detection of
numeric fields. (closes #3339)

search: no dynamic numeric fields in elasticsearch

---

elasticsearch-docker.yml
elasticsearch.yml

See [the official documentation](https://www.elastic.co/guide/en/elasticsearch/guide/current/_important_configuration_changes.html#_prefer_unicast_over_multicast) for more information on what this setting does.
We were having some troubles with records that were going missing or being added after seemingly random amounts of time. We discovered that our instances of elasticsearch were being joined into a single cluster by this feature, and we were creating and deleting records ourselves.

elasticsearch: disable multicast

---

invenio/legacy/bibindex/engine.py
invenio/legacy/bibrank/word_indexer.py

* BibIndex and BibRank uses `try` to test `insert`
when a conflict may arise. After 2.1, this fails
as the exception thrown is now an IntegrityError
Signed-off-by: Øystein Blixhavn <oystein@blixhavn.no>

legacy: replaces DatabaseError with IntegrityError in bibtasks

---

invenio/modules/deposit/helpers.py
invenio/modules/deposit/tasks.py
invenio/modules/deposit/templates/deposit/completed_base.html
invenio/modules/deposit/types/simplerecord.py
requirements-devel.txt

* Adds invenio-records the devel requirements.
* INCOMPATIBLE Reworks the default (i.e. example/simple) workflow for
deposit. SIPs are now sealed and dumped after we collected all form
data and before make ANY further modification to the deposit. This
also holds for adding the default collection information to the
deposit. Further analysis and work is required to make this process
standard compliant (e.g. splitting SIP, DIP, ...). Dumped SIPs are
now in JSON (was XML).
NOTE: This is currently only working when using the devel (i.e. unreleased) version of invenio-records. Keep this in mind when building Docker images for interactive testing. (reminder: there is an ENV-flag to control the dependency installation similar to our Travis …

deposit: fixes for JSON-based records

---

invenio/modules/deposit/bundles.py
invenio/modules/deposit/static/js/deposit/form.js
invenio/modules/deposit/templates/deposit/run_base.html

* Updates eonasdan-bootstrap-datetimepicker to 4.14.30

deposit: datetimepicker version bump

---

INSTALL.rst

* BETTER Uses sanitised variable `$BRANCH_ALNUM` (from `$BRACH` name)
in installation guide for the database name and user. (closes #3303)
(closes #3304)
Co-authored-by: Jiri Kuncar <jiri.kuncar@cern.ch>
Signed-off-by: Alexander Wagner <alexander.wagner@desy.de>
--
WDYT @aw-bib ?

installation: usage of sanitised database name

---

invenio/ext/login/__init__.py

* FIX Provides flash message to indicate that an email with password
recovery could not be sent. (closes #3309)

login: non existing user email error fix

---

invenio/modules/encoder/batch_engine.py

* FIX Corrects the `compose_file` function call in `process_batch_job`
to produce `<directory>/content.<extension>` instead of
`<directory>/content.content;<extension>` (closes #3354).
Signed-off-by: Øystein Blixhavn <oystein@blixhavn.no>

encoder: correction of function call

---

invenio/modules/oauthclient/contrib/orcid.py

* BETTER Adds ORCID id as default nickname when a user first logs in
through ORCID. (addresses #3272)

oauthclient: orcid login default nickname

---

invenio/modules/knowledge/testsuite/test_knowledge_restful.py
setup.py

* Fixes a maximum version requirement for oauthlib. (closes #3379)

global: maximum oauthlib requirement

---

invenio/modules/search/api.py

* FIX Enforces query string to be unicode to overcome pypeg2 parsing
issues.  (closes #3296)

search: fix pypeg2 unicode problem

---

INSTALL.rst

* Removes reference to --process-dependency-links when
installing Invenio as it is no longer needed. (closes #3401)

docs: --process-dependency-links removal

---

invenio/modules/deposit/config.py
invenio/modules/deposit/static/js/deposit/uploader/uploaders/dropboxuploader.js
invenio/modules/deposit/static/js/deposit/uploader/uploaders/pluploader.js
invenio/modules/deposit/templates/deposit/run_base.html

* NEW Adds configuration variable `DEPOSIT_MAX_UPLOAD_FILES_COUNT`
(specified in deposit module config file), which gives one
a possibility to limit number of files per upload.

deposit: maximum files count per upload

---

invenio/legacy/oaiharvest/daemon.py

* FIX Addresses an issue with calling six urllib.parse in a
wrong way, making users unable to harvest manually from the
command line.
Reported-by: werner.gresshoff@uni-muenster.de

legacy: oaiharvest CLI URL parse fix

---

modules/oaiharvest/lib/oai_harvest_getter.py

* FIX Fixes the parsing of resumptiontoken in incoming OAI-PMH XML
which could fail when the resumptiontoken was empty.
See legacy version in: #3297 
@aw-bib

OAIHarvest: resumptionToken fix

---

Dockerfile
INSTALL.rst
docs/getting-started/overlay.rst

Chris Lea's PPA has been deprecated since March 2015: https://nodesource.com/blog/nodejs-v012-iojs-and-the-nodesource-linux-repositories#the-nodesource-linux-repositories.
Also includes a defensive change for the Dockerfile, so that if in the future the version downloaded from `https://deb.nodesource.com/setup` changes we won't have problems.

docs: update node installation instructions

---

invenio/base/translations/af/LC_MESSAGES/messages.po
invenio/base/translations/ar/LC_MESSAGES/messages.po
invenio/base/translations/bg/LC_MESSAGES/messages.po
invenio/base/translations/ca/LC_MESSAGES/messages.po
invenio/base/translations/cs/LC_MESSAGES/messages.po
invenio/base/translations/de/LC_MESSAGES/messages.po
invenio/base/translations/el/LC_MESSAGES/messages.po
invenio/base/translations/en/LC_MESSAGES/messages.po
invenio/base/translations/es/LC_MESSAGES/messages.po
invenio/base/translations/fr/LC_MESSAGES/messages.po
invenio/base/translations/gl/LC_MESSAGES/messages.po
invenio/base/translations/hr/LC_MESSAGES/messages.po
invenio/base/translations/hu/LC_MESSAGES/messages.po
invenio/base/translations/invenio.pot
invenio/base/translations/it/LC_MESSAGES/messages.po
invenio/base/translations/ja/LC_MESSAGES/messages.po
invenio/base/translations/ka/LC_MESSAGES/messages.po
invenio/base/translations/lt/LC_MESSAGES/messages.po
invenio/base/translations/no/LC_MESSAGES/messages.po
invenio/base/translations/pl/LC_MESSAGES/messages.po
invenio/base/translations/pt/LC_MESSAGES/messages.po
invenio/base/translations/ro/LC_MESSAGES/messages.po
invenio/base/translations/ru/LC_MESSAGES/messages.po
invenio/base/translations/rw/LC_MESSAGES/messages.po
invenio/base/translations/sk/LC_MESSAGES/messages.po
invenio/base/translations/sv/LC_MESSAGES/messages.po
invenio/base/translations/uk/LC_MESSAGES/messages.po
invenio/base/translations/zh_CN/LC_MESSAGES/messages.po
invenio/base/translations/zh_TW/LC_MESSAGES/messages.po
setup.cfg

* FIX Updates PO message catalogues and cleans them of duplicated
messages.  (closes #3455)
* Adds `setup.py` Babel friendly statements.

i18n: message catalogue update and clean-up

---

setup.py

* FIX Fixes upgrader and database creation by limiting alembic
version to <0.7.
PS: I chose the same version limit as in invenio-upgrader.

global: fix alembic dependency version

---

invenio/base/templates/_macros.html

* Fix bug introduced by ecb6d6e79282fb555483d3133bf3e61dfeaf2e64.
CSS class of 'html_safe' flash messages where not displayed
properly.

base: fix flash message CSS class bug

---

invenio/ext/babel/__init__.py
invenio/modules/knowledge/testsuite/test_knowledge_restful.py
setup.py

* BETTER Improves translations lookup fallback when no compiled catalog
is found.
--
cc @hachreak

babel: fallback to NullTranslations

---

invenio/ext/login/legacy_user.py

* Sets group list on logged in user as not mandatory field.

global: optional groups field for users logged in

---

invenio/base/templates/_macros.html
invenio/base/testsuite/test_apps/__init__.py
invenio/base/testsuite/test_apps/flash_msg/__init__.py
invenio/base/testsuite/test_apps/flash_msg/views.py
invenio/base/testsuite/test_flash_security.py

* FIX Fixes display of flash messages which use "error(html_safe)"
context. They were escaped despite the "(html_safe)".
* Adds tests for standard flash message escaping.

base: fix "error(html_safe)" flash messages

---

INSTALL

* Amends documentation to warn users about not using MySQL strict
mode. (closes #905)

installation: MySQL strict mode warning

---

Dockerfile

* FIX Removes "python setup.py compile_catalog" from Dockerfile as
catalogs were removed in commit 07b2bb0.
Signed-off-by: Sami Hiltunen <sami.mikael.hiltunen@cern.ch>

docker: removal of catalog compilation

---

Procfile

* BETTER When developing and using honcho to start elasticsearch, executes
elasticsearch by storing indexes and logs within the local virtual
environment.

elasticsearch: virtualenv support

---

modules/websearch/lib/websearch_external_collections_getter_tests.py

* FIX Fixes asynchronous external collection getter tests following the
update of the Invenio project web site.

WebSearch: fix async getter tests

---

.travis.yml
docs/conf.py
docs/deprecationpolicy.rst

* Amends Travis CI configuration in order to build documentation only,
following up the separation of `invenio-base` and related packages.
* Amends documentation in a minimal manner to ensure the build passes.
The content of the documentation will be enriched subsequently.

travis: retain documentation building only

---

Dockerfile
INSTALL.rst
docs/configuration/overlay.rst

The `.bowerrc` file shouldn't live in the overlay as it is meant to be installed as a package too. In the meantime, invenio can safely use nodejs-4.x the son of io.js and node.js pre-Node.js foundation.

Nodejs and bower changes

---

invenio/legacy/search_engine/__init__.py

**What I did**
I was visiting a collection page, e.g. `/search?cc=Photo&ln=en`
**What happened**
```
Traceback (most recent call last):
File "/home/invenio/.virtualenvs/maint-2.0/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__
return self.wsgi_app(environ, start_response)
File "/code/invenio/invenio/ext/legacy/__init__.py", line 128, in __call__
response = self.app.handle_exception(e)
File "/home/invenio/.virtualenvs/maint-2.0/lib/python2.7/site-packages/Flask_RESTful-0.3.4-py2.7.egg/flask_restful/__init__.py", line 270, in error_router
return original_handler(e)
File "/home/invenio/.virtualenvs/maint-2.0/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File …
```

search: intbitset could be None

---

setup.py

Fixes the `entry_point` as pip 7.x expects a function and not a module.

installation: fix entry_points for pip7

---

.travis.yml
CHANGES.rst
RELEASE-NOTES.rst
invenio/version.py
setup.py

See https://gist.github.com/lnielsen/982d3ea51d2d69983bce

Invenio v3.0.0a1

---

invenio/base/bundles.py
invenio/base/templates/base/scripts_base.html
invenio/ext/assets/commands.py
invenio/ext/assets/wrappers.py

Some libraries like MathJax or jQuery are very common, sometimes hard to bundle, and may be loaded from their CDN.
**Example**
How to load MathJax and jQuery from their CDNs.
```python
from invenio.base.bundles import jquery as _jquery
_jquery.bower["MathJax"] = "~2.5"
_jquery.bower["jquery"] = ("//code.jquery.com/jquery-1.11.3.min.js", "~1.11")
```
```javascript
// my-overlay/base/static/js/my-overlay-settings.js
require.config({
paths: {
jquery: ["//code.jquery.com/jquery-1.11.3.min.js",
"vendors/jquery/dist/jquery.min"],
// ...
```
```javascript
// my-overlay/base/static/js/build.js
({
// ...
mainConfigFile: ["./settings.js", "my-overlay-settings.js"],
paths: {
"jquery": "empty:"
}
})
```
**Result**
Bower.json will have `jquery` but not `MathJax`.
```json
{
"dependencies": {
"jquery": …
```

global: assets loaded from their CDN

---

setup.py

* Adds extra requirements groups that proxy dependencies for
*Invenio-DB*.  (addresses #3566)

installation: extra dependencies for db drivers

---

docs/configuration/overlay.rst
docs/installation/installation-detailed.rst
docs/technology/docker.rst
scripts/install.sh
scripts/provision-web.sh

* BETTER Amends installation scripts and instructions to use `npm`
instead of `bower`. (closes #3568)

installation: migration from `bower` to `npm`

---

scripts/install.sh

* BETTER Amends installation scripts and documentation to use the
recently released `Invenio-Records` and `Invenio-PIDStore` PyPI
packages. The record IDs are now internally represented by UUIDs.

installation: latest record packages

---

Vagrantfile
scripts/install.sh
scripts/provision-elasticsearch.sh
setup.py

* BETTER Amends installation scripts and documentation to use the
recently released `Invenio-Search` module providing record indexing in
Elasticsearch.
* Completes Elasticsearch host provisioning script to allow network
connections.
* Gives all Vagrant boxes explicit names to ease orientation.

installation: addition of `Invenio-Search` module

---

invenio/ext/script/__init__.py

Serves the .mustache templates as `text/html` instead of  `application/octet-stream` from the develpment server. Those files are compiled via hgn in production anyways. The developer tools will be able to show their content from now on.

global: mustache templates as text/html

---

invenio/ext/iiif/__init__.py

* FIX Changes `IIIF_CACHE_HANDLER` to fallback to invenio cache.
Signed-off-by: Harris Tzovanakis <me@drjova.com>

iiif: set default cache handler properly

---

README.rst
docs/installation/installation-detailed.rst
scripts/install.sh
scripts/provision-postgresql.sh
setup.py

* BETTER Amends installation scripts and documentation to use the
recently released `Invenio-Base` package where `manage.py` was removed
in profit of `setup.py`. (closes #3572)
* Amends README file to mention PostgreSQL and SQLite alongsite MySQL in
the list of supported databases.

installation: latest base package

---

Dockerfile
docs/installation/installation-detailed.rst
scripts/provision-elasticsearch.sh
scripts/provision-postgresql.sh
scripts/provision-rabbitmq.sh
scripts/provision-redis.sh
scripts/provision-web.sh
scripts/provision-worker.sh

* Uses slim Python Docker image and cleans locally cached system
packages that are no longer necessary after provisioning the nodes.
Helps to reduce the size of virtual machines and of Docker containers.

installation: node provisioning cleanup

---

docker-compose.yml

* Amends RabbitMQ Docker container's port exposure to use the higher
port (by adding 20000 to the usual port), so that one can run
docker-based installation alongside OS-based installation without
having to shutting down any locally installed system services.

docker: rabbitmq port exposure

---

Dockerfile
MANIFEST.in
docker-compose.yml
nginx/Dockerfile
nginx/invenio3.conf
scripts/start-instance.sh

* Amends Docker installations instructions to be both GNU/Linux native
friendly and remote docker-machine VM friendly. (closes #3595)
* Adds Nginx front-end support for static files.
* Removes `--debug` flag when starting the Invenio instance.
* Adds temporary fix for `SQLAlchemy-Utils` on Ubuntu 14.04 that is
encountered also on Docker images.

installation: docker-machine friendly instructions

---

Dockerfile
MANIFEST.in
docker-compose.yml
nginx/Dockerfile
nginx/invenio3.conf
scripts/create-instance.sh
scripts/start-instance.sh

* Fixes account login/register facility in the demo site. (closes #3602)
* Amends Redis and RabbitMQ configuration.

installation: fix account login/register

---

docker-compose.yml
scripts/create-instance.sh

* Copies files to the 'static' node instead of linking them.

docker: static files location fix

---

config/invenio.conf

* FIX Fixes default configuration of CFG_OAI_METADATA_FORMATS,
correctly assigning the XSD and XML namespace to the corresponding
metadata prefix.

OAIRepository: CFG_OAI_METADATA_FORMATS fix

---

CONTRIBUTING.rst

* Updates some of the links to the new invenio.readthedocs.org domain
* Removes links that do not have a direct match in the new docs
github: closes #3557
@jirikuncar @tiborsimko please review if the all links are appropriate or if there are some suitable ones for the ones I removed

docs: fix broken contributing links

---

setup.py

* FIX Adds upper limit on the Flask-Babel packages version, fixing
installation troubles.

installation: upper limit on Flask-Babel

---

Vagrantfile
modules/bibformat/lib/bibreformat.py
modules/bibindex/lib/bibindex_engine.py
modules/bibrank/lib/bibrank_citation_indexer.py
modules/bibrank/lib/bibrank_citerank_indexer.py
modules/bibrank/lib/bibrank_tag_based_indexer.py
modules/bibrank/lib/bibrank_word_indexer.py
modules/bibupload/lib/bibupload.py
modules/bibupload/lib/bibupload_regression_tests.py
modules/miscutil/lib/inveniocfg.py
modules/webaccess/lib/access_control_firerole.py
modules/webbasket/lib/webbasket_dblayer.py
modules/webcomment/lib/webcomment.py
modules/webcomment/lib/webcommentadminlib.py
modules/websearch/lib/websearch_webcoll.py
modules/websession/lib/session.py
modules/websubmit/lib/bibdocfile.py
scripts/drop-instance.sh

* FIX Silences most MySQL UTF-8 warnings related to inserting into and
updating BLOB table columns.

global: silencing MySQL UTF-8 warnings for BLOBs

---

Makefile.am

* BETTER Pinned specific JSON-js and Mediaelement versions instead of
using the latest master branch commits. (closes #11)

installation: pinned JSON-js Medialeement versions

---

modules/websession/lib/session.py

* Silences one more MySQL UTF-8 warnings related to session object
updating.

WebSession: silencing MySQL UTF-8 warnings

---

Makefile.am
requirements.txt
scripts/create-instance.sh

* FIX Amends installation procedures to download necessary jQuery
plugins from Invenio-hosted web site, fixing problems with
non-existing Google Code pages. (closes #3620)

installation: Invenio hosting of jQuery plugins

---

scripts/provision-web.sh

* Provisions the web node with `h5py` dependency that is needed for
BibAuthorID module. Fixes one failed unit test case.

installation: web node h5py provisioning

---

modules/bibcatalog/lib/bibcatalog_system_email_unit_tests.py
scripts/provision-web.sh

* Skips running email test suite when the SMTP server is not available.
Fixes four failed tests on Travis CI.

BibCatalog: no email tests when no SMTP server

---

modules/websearch/lib/websearch_regression_tests.py

* FIX Fixes a search regression test case that looks for records added
in the past 10 years. This test started to fail because some records
are declared with date added (see MARC tag 005) before 2006. Amends
the test case to use safer value of last 100 years instead of last 10
years.

WebSearch: fix for da today 3650 test case

---

modules/websession/lib/websession_regression_tests.py
scripts/provision-web.sh

* Makes sure that Apache and Redis are started right after provisioning.
Fixes a problem on Travis CI when not using their built-in Redis
service.

installation: Apache and Redis start-up

---

INSTALL
scripts/create-instance.sh
scripts/drop-instance.sh
scripts/populate-instance.sh
scripts/provision-mysql.sh
scripts/provision-web.sh

* BETTER Uses `/usr/sbin/service foo` consistently everywhere to restart
daemons instead of deprecated `/etc/init.d/foo`.
* This fixes some troubles seen on Travis CI in higher `maint-1.2`
branches.

installation: use of `/usr/sbin/service`

---

docs/conf.py
scripts/provision-web.sh
setup.py

* Uses the presence of either `/.dockerenv` or `/.dockerinit` file to
detect whether the web provisioning script runs inside the Docker
container. (The `/.dockerinit` file was removed in recent Docker
versions.)

installation: better Docker detection

---

ABOUT-NLS
AUTHORS.rst
README.rst
RELEASE-NOTES.rst
docs/configuration/overlay.rst
docs/introduction/demo.rst
docs/technology/git.rst
setup.cfg
setup.py

* Changes `invenio-software.org` to `inveniosoftware.org` to use the
same dashless canonical ID everywhere (GitHub, Twitter, Web).

global: inveniosoftware.org

---

modules/websession/lib/webgroup_dblayer.py

* FIX Removes pending groups from user info object.  (closes #3526)
Reported-by: Bessem Aamira <bessemamira@gmail.com>

WebSession: excluding pending groups

---

.inveniorc
Dockerfile
INSTALL.rst
Vagrantfile
docs/architecture/system-overview.rst
docs/installation/installation-detailed.rst
docs/installation/installation-quick.rst
docs/introduction/releases.rst
scripts/create-instance.sh
setup.py

* The example installation procedures now use Invenio PyPI packages
instead of GitHub bleeding-edge versions. (In other words,
``scripts/create-instance.sh`` does not use ``--devel`` argument by
default anymore.)
* Increases minimal versions of required Invenio PyPI packages to the
latest recommended versions.

installation: PyPI packages in kickstart scripts

---

modules/bibsched/lib/tasklets/bst_create_icons.py

* FIX Makes `recid` argument optional in tasklet `bst_create_icons`.
(closes #2192)

BibSched: fix required args in bst_create_icons

---

docs/processes/developing.rst
docs/processes/integrating.rst
docs/processes/releasing.rst
docs/processes/reporting.rst
docs/processes/reviewing.rst
docs/processes/sprinting.rst
docs/processes/triaging.rst

* Improves verbiage of several process principles, such as avoiding
self-merges or starting sprints with kick-off meetings. (closes #3659)
* Adds anchors to all process principles to make them easily citeable.
Example: `/processes/integrating.html#avoid-self-merges`.

docs: process principle improvements and anchors

---

README.rst

- Remove link to non-existing `LICENSE` file and replace with correct
link (Closes #3682)
Signed-off-by: Achintya Rao <achintya.rao@cern.ch>

docs: Fix link to COPYING in README

---

nginx/invenio3.conf

* Updates the ``Host`` header value in order to use ``$http_host`` variable which also contains the port that the browser is sending.
Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

installation: fix of nginx host header

---

requirements.txt

* FIX Amends canonical location of py-editdist and pyRXP packages,
fixing the installation problem.

installation: safer editdist/pyRXP hosting

---

MAINTAINERS

docs: maintainer email address fix

---

NEWS
modules/websession/lib/inveniogc.py

* FIX Fixes garbage collection of temporary directories created by
websubmit_icon_creator and websubmit_file_stamper.
(closes #3556) (PR #3558)
Signed-off-by: Alexander Wagner <alexander.wagner@desy.de>

inveniogc: better tempdir deletion

---

modules/bibdocfile/lib/bibdocfile.py

* FIX Purges old extracted text too, when purging a BibDoc.
(closes #3519)

BibDocFile: purging extracted text

---

modules/miscutil/lib/urlutils.py

* BETTER Uses `md5` from `hashlib` when available. (closes #3382)

urlutils: hashlib and md5

---

docker-compose.yml
setup.py

* FIX Pins Elasticsearch PyPI dependencies to use version 2 and
configures Docker to use Elasticsearch version 2 rather than version 5
for which some of the Invenio packages are not ready yet. This
harmonises the use of Elasticsearch version 2 for both Docker and
Vagrant based installation procedures. (closes #3714)
* Increments versions of several Invenio packages.

installation: Elasticsearch 2 in Docker

---

Dockerfile

* FIX Removes jQuery plugin installation step for this very old release, as is
the case in `scripts/create-instance.sh` based installations. This fixes the
Docker installation process at the price of missing jQuery plugins.

docker: no installation of jQuery plugins

---

config/invenio.conf
modules/bibdocfile/lib/bibdocfile_managedocfiles.py
modules/bibformat/lib/elements/bfe_edit_record.py
modules/bibindex/lib/tokenizers/BibIndexFulltextTokenizer.py
modules/miscutil/lib/solrutils_bibrank_indexer.py
modules/websearch/lib/search_engine.py
modules/websession/lib/webuser.py
modules/webstyle/lib/webinterface_handler_wsgi.py
modules/websubmit/lib/websubmit_file_converter.py

* FIX Takes into account the sort order when searching, even if
no specific sort or rank method is used. (PR #3564)
* Issue introduced in e49a1368bb0e4159b3a43b508140db120c2e8e82.
Signed-off-by: Ludmila Marian <ludmila.marian@gmail.com>

WebSearch: consider sort order when searching

---

Dockerfile
INSTALL

* FIX Fixes Docker build instructions by updating `pip` statements regarding
`supervisor` and by removing remaining references to nowadays removed
requirements extras list.

docker: fix installation instructions

---

scripts/create-instance.sh

* BETTER Uses `jinja2-cli>=0.6.0` for simplified config generation.
(closes #3753)

scripts: support for jinja2-cli>=0.6.0

---

INSTALL.rst

It appears this link wasn't updated when documentation was moved?

Correct link to readthedocs

---

scripts/instance.cfg

* Disable Talisman session_cookie_secure to be able to login
without HTTPS. (closes #3815)

invenio: disable Talisman session_cookie_secure

---

CONTRIBUTING.rst
docs/quickstart.rst

- Used long form options so that commands are less
cryptic to newcomers
- Denoted the virtualenv used so that it is clear
in what context are the libraries installed and
usable
- Marked nodejs6+ and npm4+ as working
(made it work on npm 5.6.0 and node 8.11.2)
These are all additions from the point of view of
someone new to the project (i.e. things that tripped me up!).

docs: Improve quickstart docs + fix typos

---

docs/quickstart.rst

- Updated the copyright notice
- Added a section on installing cookiecutter outside of 
the project's virtualenv since it is also used for invenio 
modules and data records. It is a tool worth having 
everywhere and will simplify documentation for the
Module Tutorial.
- Displayed the output of the cookiecutter call so that
various names are explicit to the reader.

docs: document cookiecutter install + instance output

---

.travis.yml
invenio/version.py
setup.py

Packages invenio-previewer and invenio-iiif are still in alpha version.
Remove tests for ES2 as it is deprecated.
closes #3939

release: v3.2.0a1

---

MANIFEST.in
docs/index.rst
docs/tutorials/upgrade-marshmallow.rst

Small guide on how to upgrade to marshmallow3
to integrate it with upgrade to v3.2

docs: marshmallow upgrade guide

---

docs/index.rst
docs/upgrading.rst

Continued from https://github.com/inveniosoftware/cookiecutter-invenio-instance/pull/181
* Pipfile
* Files
* Database
* Elasticsearch
I tested starting an Invenio 3.1 cookiecutter instance and upgraded it to Invenio 3.2 with no issues.
Closes #3951

docs: add upgrade guide from 3.1 to 3.2

---

setup.py

Pin werkzeug to greater than 0.15 and lower than 1 to fix the broken imports temporarily.

dependencies: pin werkzeug (broken imports)

---

docs/documentation/bundles/alpha.rst
docs/documentation/bundles/documentation.rst
docs/documentation/bundles/index.rst
docs/documentation/bundles/scaffolding.rst
docs/documentation/bundles/utilities.rst

Closes #4058 
**Notes**:
- Some modules like `.github`, `automation-tools`, etc. have been left out since they are utility modules to manage Invenio, but not Invenio modules *per se* or CERN specific (e.g. `cernservicexml`).
- RDM modules are all included in `alpha.rst`.
- Utility modules are in `utilities.rst` even if they are in alpha state, because this was the pattern with others like `citeproc-py-styles`.
- Some modules (e.g. babel-edtf) have their docs page broken (not built?)
- https://babel-edtf.readthedocs.io
- https://helm-invenio.readthedocs.io
- https://invenio-banners.readthedocs.io
- https://invenio-cli.readthedocs.io/en/latest/ Should just point to https://inveniordm.docs.cern.ch/reference/cli/
- https://invenio-records-editor.readthedocs.io
- …

docs: update list of modules

---

README.rst
docs/conf.py
docs/getting-started/development-environment.rst

:heart: Thank you for your contribution!
Please describe briefly your pull request.
Fix #4092
* Improved English
* Improved formatting
* Standardise CLI commands
* Remove commands for `n` tool for node
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your …

Fix typos and standardise commands
